### ISSUE TITLE
갤번역 중에 빠진거

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#100]
내가 대리 업로드로 MOD KOREAN TRANSLATE 에다 올린건데

RKM에 빠진게 있더라고

[빠진거.zip](https://github.com/RimWorldKorea/RMK/files/13388443/default.zip)

그리고

ↁ Elves - 2905623211
Elves - 2905623211

두개가 있는데 아래 기호 없는게 내가 추가한 최신본임

기호 있는건 지워도 될듯

**Comment by RimWorldKorea** [comment]
#60

**Comment by RimWorldKorea** [comment]
Medieval Overhaul Extra Signs - 2967087032 별도 이슈로

**Comment by RimWorldKorea** [comment]
c08be8565a6d97e6fc22b9df94b5f7c9b70d99de

**Comment by RimWorldKorea** [comment]
아 RMK에 같은게 두 개 들어갔단 말이구나
