### ISSUE TITLE
Glitter Tech

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#102]
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

[콜딩](https://steamcommunity.com/id/karyuru) 7시간 전 
RKTM에 포함된 Glitter Tech 이 모드도 번역에서 제외된거 같네요

**Comment by RimWorldKorea** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2558099206
