### ISSUE TITLE
Vanilla Aspirations Expanded

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#1041]
소스: https://gall.dcinside.com/m/rimworld/532163
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3268401022
파일: [Vanilla Aspirations Expanded - 3268401022.zip](https://github.com/user-attachments/files/15874179/Vanilla.Aspirations.Expanded.-.3268401022.zip)

**Comment by sam09036** [comment]
[Languages.zip](https://github.com/user-attachments/files/15900064/Languages.zip)
조사 수정본
