### ISSUE TITLE
Edo Themed Expansion

### ISSUE THREAD

**Issue by Qooowl** [RimWorldKorea/RMK#1065]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2878807817
- 모드 이름 : Edo Themed Expansion
- 패키지ID : 2878807817

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [ ] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [x] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p><일본 에도 시대풍 가구, 무기, 헤어, 바이옴, 세력, 건물 등이 추가되는 모드입니다. ps. 번역 요청은 처음인지라 미숙한 점이 있었다면 양해부탁드립니다.>

**Comment by RimWorldKorea** [comment]
조사 결과 [구버전](https://steamcommunity.com/sharedfiles/filedetails/?id=2579463751)을 통틀어서 기존 번역 작업물의 존재를 확인할 수 없었습니다.
이전에 번역이 된 모드였다면 저희가 데이터를 찾을 수 있도록 사용했던 번역 모드 등을 확인하여 알려주세요!
