### ISSUE TITLE
Vanilla Races Expanded - Android

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#1183]
소스: [창작마당](https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972)
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=2975771801
>[Matstar](https://steamcommunity.com/profiles/76561197996888574)
바익 안드로이드 keyed에 인공 장기 번역에 변수가 없어서
모든 부위의 물건이나 레시피가 '인공'으로만 나옵니다.

#668 문제로 보임

**Comment by gogochlwns** [comment]
제보시 같이 올려둔 imgur 이미지대로 수정시 올바르게 출력됩니다.

https://imgur.com/a/nHhvuZC
