### ISSUE TITLE
[LSK]Rabbie Defense And Turrets

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#1198]
소스: https://gall.dcinside.com/m/rimworld/539682
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3189955293
파일: [[LSK]Rabbie Defense And Turrets.zip](https://github.com/user-attachments/files/16319071/LSK.Rabbie.Defense.And.Turrets.zip)

**Comment by RimWorldKorea** [comment]
모드가 그새 많이 바뀐건가? 안 맞는게 왜이리 많지

**Comment by RimWorldKorea** [comment]
왜 다시 추출하니깐 잘 나오지?

**Comment by zilrty** [comment]
뭐 추가 된거 없을텐데 번역 업뎃할게 있나?

**Comment by RimWorldKorea** [comment]
전반적으로 좀 다듬어진것도 있고 그렇든대

**Comment by zilrty** [comment]
이 아조씨랑 나랑 번역한게 달라서 용어 통일이 안된거 같긴하지만 신경 안쓰겠지?
