### ISSUE TITLE
NamesInYourLanguage 20240809 번역 갱신

### ISSUE THREAD

**Issue by Curry0321** [RimWorldKorea/RMK#1256]
[Translations.txt](https://github.com/user-attachments/files/16562361/Translations.txt)

한번에 해달라고 했는데 양이 너무 많아..

그래도 일단 ->a ,->b ....->z 이런식으로 검색해서 영어로 나오는것들 한글화함.

검수는 데보라인가 거기까지 갔음 한 15% 했나?

진짜 가시성 좋아진김에 검수 하기를 잘함. 

근데 수정하고 나서 대괄호 부분 <이름::별명::성>은 안바뀌는거야? DB같은 형태임? 

수정을 해도 저건 예전버전 그대로더라고

영어로 나오는것들때매 갱신한거고 다음부턴 많이 진행하고 갱신할게

**Comment by RimWorldKorea** [comment]
대괄호 부분은 수정 파일을 적용한 채로 새로 뽑으면 수정한 대로 나올거예요

**Comment by RimWorldKorea** [comment]
이 기능 만들때 원문만 보려고 만들어둔거라 번역된걸로 갱신하도록 고려하진 않았네요
나중에 생각나면 옵션같은거 만들어둠
생각나면..

**Comment by Curry0321** [comment]
> 이 기능 만들때 원문만 보려고 만들어둔거라 번역된걸로 갱신하도록 고려하진 않았네요 나중에 생각나면 옵션같은거 만들어둠 생각나면..

해줘!
