### ISSUE TITLE
Dubs Bad Hygiene - Thirst

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#1266]
소스: 창작마당
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=2582878800

>[aaasioa](https://steamcommunity.com/profiles/76561198039635481)
Dubs Bad Hygiene 의 lite 버젼으로 분화되어 나온 Dubs Bad Hygiene - Thirst

**Comment by zilrty** [comment]
이거 포함 밑에 두개 하다가 뭔가 꼬여서 걍 냅둠 ㅋㅋ

아조씨가 '해줘'

**Comment by RimWorldKorea** [comment]
풀버전 컨텐츠 일부를 라이트 버전에 추가시키는 애드온

어차피 라이트 버전이 풀버전 번역 폴더를 참조하도록 돼있기 때문에
이미 적용이 돼있을건데

**Comment by RimWorldKorea** [comment]
DB 메모에 내용 기록만 해둠
