### ISSUE TITLE
边缘仙路-羽化登仙 RimImmortal-Core[1.5]

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#1277]
소스 : https://gall.dcinside.com/m/rimworld/553299
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=3296476341
파일 : [RimImmortals-Core - 3240134104.zip](https://github.com/user-attachments/files/16835796/RimImmortals-Core.-.3240134104.zip)

**Comment by RimWorldKorea** [comment]
#1300 으로 점프

**Comment by RimWorldKorea** [comment]
#1300 은 조사가 필요한 파일이라 이거 먼저 등록
