### ISSUE TITLE
NamesInYourLanguage 외지인 고정 이름에 붙는 동물별명들

### ISSUE THREAD

**Issue by Curry0321** [RimWorldKorea/RMK#1288]
여기 없는 동물 이름 Tiger라든가 청어 Herring 이라든가 이름이나 성씨가 되는것들은 제외됨. 

게임내 필드에 등장하는 동물 (음차 x)
Squirrel 다람쥐(이거는 성장배경 설명에 다람쥐가 박혀있음)
Panther Tortoise Horse Deer Duck Cow Pig Raccoon Monkey Goose Turkey Rhino Lynx Hamster

한글 음차표기로 쓰이는것들
Hyena Coyote Gorilla Cobra Jackal Beaver Armadillo Penguin Gerbil Wombat Skunk Meerkat llama Koala Panda 

음차하면 의미전달이 어려워보이는 것들 (음차 x)
Walrus 바다코끼리 Mule 노새 Mole 두더지 Weasel 족제비 
Gnat Ape Magpie Parrot Ferret Shrew Snail Owl
Newt 영원류 총칭인데 RMK말고 Core 한국어파일 부족민 동물이름엔 맹꽁이로 있음. 샐러맨더가 도룡뇽이라 한거같긴함.
Sardines 정어리 이것도 Core 영어파일엔 Sardine 인데 도요새로 나오게됨. 이건 완벽한 오역

고민중인 것들
Shark (샤크or 상어)
Spider Snake Viper Scorpion
Snipe 저격이냐 도요새냐
Moose 무스냐 엘크냐 말코손바닥사슴이냐
Condor Flamingo Mantis Lion Ant Toad Frog Hedgehog Lizard Dog Hippo Dolphin Turtle Crab Shrimp Tunafish Lungfish Catfish Rabbit Salmon 

그외 
Goat (그냥 영문으로 Goat 나오게함)
Chicken (닭말고 중의적인 의미때매 치킨)
Reptile (렙틸이냐 파충류냐)
Mouse (쥐랑 컴퓨터 마우스)
Bat (바톨로뮤라는 이름을 가진 폰1명의 별명인데 바트 심슨 본명 생각나서 이름 별명같기도 하고 박쥐냐 빠따냐 일수도 있어서)
Dragon (상상의 동물은 음대로)
Jackalope (상상의 동물)
Pegasus (상상의 동물)
Cub (새끼곰 할까 커브로 둘까)

방향성 의견좀 부탁

**Comment by RimWorldKorea** [comment]
디스코드로 이관
