### ISSUE TITLE
Biological Warfare

### ISSUE THREAD

**Issue by basalt991** [RimWorldKorea/RMK#1299]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=3221550806
- 모드 이름 : Biological Warfare
- 패키지ID : 3221550806
- 번역본 : https://drive.google.com/file/d/1PMFsRQ2Kmhi6R87Y6pFqV3B4NcQd4dY9/view?usp=drive_link

**Comment by RimWorldKorea** [comment]
파일: [Ushankas Biological Warfare - 3221550806.zip](https://github.com/user-attachments/files/17177836/Ushankas.Biological.Warfare.-.3221550806.zip)
