### ISSUE TITLE
Therapy

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#133]
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

[NUEE](https://steamcommunity.com/profiles/76561198019598802) 21시간 전
이 모드로 대체하고 한글 번역 풀린 모드입니다.
Human Power Generator Mod, Therapy, Haul Explicitly, RIMkea.
RKTM에서 번역해줬던 모드라 제보합니다.

**Comment by RimWorldKorea** [comment]
무덤에서 확인
