### ISSUE TITLE
Haul Explicitly

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#134]
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

[NUEE](https://steamcommunity.com/profiles/76561198019598802) 21시간 전
이 모드로 대체하고 한글 번역 풀린 모드입니다.
Human Power Generator Mod, Therapy, Haul Explicitly, RIMkea.
RKTM에서 번역해줬던 모드라 제보합니다.

**Comment by RimWorldKorea** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2912298699 1.4
https://steamcommunity.com/sharedfiles/filedetails/?id=1547394294 1.3

**Comment by RimWorldKorea** [comment]
PKTE 파일 확인
