### ISSUE TITLE
충돌 이슈

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#1350]
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972&tscn=1731400270

[DinerBoom](https://steamcommunity.com/id/DinerBoom) 2024년 11월 11일 오후 7시 16분 
RMK번역이 'Hellsing ARMS Ultimate' 이거랑 충돌을 일으키나봅니다.
로그는 안남는데 초록구울, 노란구울로 변하고 나서 바디 색상이 투명화됩니다.
일단 임시방편으로 번역파일을 빼놓고 하고있긴합니다.
[https://steamcommunity.com/sharedfiles/filedetails/?id=2834801420](steam://openurl/https://steamcommunity.com/sharedfiles/filedetails/?id=2834801420)

**Comment by zilrty** [comment]
확인해봤는데 진짜 바디 텍스쳐가 투명해지긴함

RMK빼면 멀쩡해짐

**Comment by RimWorldKorea** [comment]
HAR이면 번역하면 안되는거 번역한거일듯

**Comment by zilrty** [comment]
아하 확인함

**Comment by zilrty** [comment]
업뎃은 귀찮으니까 내일 하겠음
