### ISSUE TITLE
UNAGI Royalty Apparel - 3352990362

### ISSUE THREAD

**Issue by moonjigi0723** [RimWorldKorea/RMK#1353]
<b>번역 출처</b>
- 주소 :

<b>모드 정보</b>
- 창작마당 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=3352990362
- 모드 이름 : UNAGI Royalty Apparel
- 패키지ID : unagi.ap.dress

<b>첨부 파일</b><p>

<b>기타 참고 사항</b>

**Comment by zilrty** [comment]
첨부파일이 빠져있어요

**Comment by moonjigi0723** [comment]
[UNAGI Royalty Apparel - 3352990362.xlsx](https://github.com/user-attachments/files/17823689/UNAGI.Royalty.Apparel.-.3352990362.xlsx)
