### ISSUE TITLE
[RF] Rational Romance (Continued) - 2013144996

### ISSUE THREAD

**Issue by uwu1004** [RimWorldKorea/RMK#1381]
<b>번역 출처</b>
- 주소 :

<b>모드 정보</b>
- 창작마당 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2013144996
- 모드 이름 : [RF] Rational Romance (Continued)
- 패키지ID : Mlie.RationalRomance

<b>첨부 파일</b><p>

[[RF] Rational Romance (Continued) - 2013144996.zip](https://github.com/user-attachments/files/17825648/RF.Rational.Romance.Continued.-.2013144996.zip)

<b>기타 참고 사항</b>

**Comment by zilrty** [comment]
keyed 번역이 안돼있어요잉

**Comment by uwu1004** [comment]
[[RF] Rational Romance (Continued) - 2013144996.zip](https://github.com/user-attachments/files/17827289/RF.Rational.Romance.Continued.-.2013144996.zip)

**Comment by uwu1004** [comment]
죄송합니닷!!!!! 다시 올려요!!!!!!
