### ISSUE TITLE
Weapons+

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#140]
#136
https://steamcommunity.com/sharedfiles/filedetails/?id=1578914181

**Comment by RimWorldKorea** [comment]
[RKTM]MOD-unconfirm 폴더 존재 확인
처리 불가능

**Comment by RimWorldKorea** [comment]
@sra23142

**Comment by sra23142** [comment]
@RimWorldKorea 

이 모드 예전에, 일부 번역이 되어있었던걸로 기억해서 제보 드렸습니다
확실하지 않고, 번역이 절실하지도 않은 모드라 폐기해주셔도 괜찮을것 같습니다

노고 감사드립니다
