### ISSUE TITLE
Vanilla Animals Expanded

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#1441]
소스 : 
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=2871933948
파일 : [Vanilla Animals Expanded - 2871933948.zip](https://github.com/user-attachments/files/18218094/Vanilla.Animals.Expanded.-.2871933948.zip)

------------------
[Jhagatai](https://steamcommunity.com/profiles/76561197997870504) 11시간 전 
[https://steamcommunity.com/sharedfiles/filedetails/?id=2871933948](steam://openurl/https://steamcommunity.com/sharedfiles/filedetails/?id=2871933948)
바닐라 애니멀 익스팬디드에서 keyed 부분이 영어로 나옵니다. rktm에서는 한국어로 잘 나왔습니다.

**Comment by RimWorldKorea** [comment]
첨부 파일은 그냥 있던 파일임?

**Comment by zilrty** [comment]
> 첨부 파일은 그냥 있던 파일임?

빠진부분 채워넣은 파일임
