### ISSUE TITLE
마루 모드 트레잇 및 성장환경 오타

### ISSUE THREAD

**Issue by AfxousaAjagara** [RimWorldKorea/RMK#1456]
<b>모드 정보</b><p>

- 창작마당 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2817638066
- 모드 이름 : 마루 종족모드
- 패키지ID : vamv.maruracemod

<b>세부 설명 및 첨부 파일</b><p>
1.
![image](https://github.com/user-attachments/assets/1b40eadf-3d49-40f4-986a-55537c51a41a)

2.
![image](https://github.com/user-attachments/assets/16ace702-1b81-48a2-b569-bb955849d697)

마루 트레잇과 성장환경에 오타가 있습니다.

**Comment by AfxousaAjagara** [comment]
![image](https://github.com/user-attachments/assets/537ecdc9-851b-44cb-9141-e0ce312677e5)
성장 환경에 미번역분도 있는것으로 보입니다

**Comment by zilrty** [comment]
엥 마루 국산모드 아니었나

**Comment by zilrty** [comment]
마루는 모드 자체에서 한글을 지원하는 국산모드라 RMK에 번역 자체가 없음

마루 모더한테 문의하심이...

**Comment by AfxousaAjagara** [comment]
감사합니다. 마루 모드도 여기에서 담당하는줄 알았네요.
