### ISSUE TITLE
Pharmacist Temporary 1.4 Update

### ISSUE THREAD

**Issue by sra23142** [RimWorldKorea/RMK#171]
https://steamcommunity.com/sharedfiles/filedetails/?id=2880823401&searchtext=pharmacist

**Comment by RimWorldKorea** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2880823401
https://steamcommunity.com/sharedfiles/filedetails/?id=1365242717

**Comment by RimWorldKorea** [comment]
무덤에서 확인
