### ISSUE TITLE
EvolvedOrgansRedux

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#18]
2424381146

일부 번역이 안된다고 함
#22 #23 이후 재확인 필요

**Comment by zilrty** [comment]
원래 전부 번역 되있던 모드 맞음?

원 모드 업뎃 때문에 번역 못한거 빼고는 다나오는거 같은데

**Comment by RimWorldKorea** [comment]
[https://docs.google.com/spreadsheets/d/1na13zJwwKcSk4FeHgeGalNrgk0vc78_Y9fMOhCdBqf0/edit?usp=sharing](url)
그런건 DB에 메모해두고 치워두면 됨
