### ISSUE TITLE
[WD] Reinforced Doors

### ISSUE THREAD

**Issue by temporarygithubgeek** [RimWorldKorea/RMK#180]
[모드 정보]
- 워크샵 주소: https://steamcommunity.com/sharedfiles/filedetails/?id=1857597307
- 모드 이름: [WD] Reinforced Doors
- 패키지ID: wemd.reinforceddoors

[확인 사항]
- [번역 목록]에 모드가 등재되어 있나요? [N]
- 이전에 번역이 되었던 부분에 대한 문제인가요? [Y]

[첨부 파일]
RKTMModv1\Languages\Korean (한국어)\DefInjected\ThingDef\Reinforced_Doors-1857597307.xml

**Comment by RimWorldKorea** [comment]
#154
