### ISSUE TITLE
[RKTM]MOD-unconfirm

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#182]
받을때 에러 뜨긴하던데 써먹을 수 있을듯?

언컨펌 구하는것 같아서 올려봄

[2603339663.zip](https://github.com/RimWorldKorea/RMK/files/13463381/2603339663.zip)

**Comment by RimWorldKorea** [comment]
난 이거 파일이 하나도 안받아지고 스팀만 맛가던데 ㅋㅋ

**Comment by RimWorldKorea** [comment]
이것도 0바이트 파일인데??

**Comment by RimWorldKorea** [comment]
이것도 파일없고 폴더만 있네?
