### ISSUE TITLE
More Thrumbos (Retextured)

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#198]
#197

https://steamcommunity.com/sharedfiles/filedetails/?id=2849164933

**Comment by RimWorldKorea** [comment]
@moonjigi0723

<img src="https://private-user-images.githubusercontent.com/152117758/285697237-cee2ddf2-79a4-4041-904d-f51a7c1cefc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwOTE1NzIsIm5iZiI6MTcwMTA5MTI3MiwicGF0aCI6Ii8xNTIxMTc3NTgvMjg1Njk3MjM3LWNlZTJkZGYyLTc5YTQtNDA0MS05MDRkLWY1MWE3YzFjZWZjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMzIxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjA0YWMxMzdlYzY5OGMxYjZiMGJlMDA0YzE4NDk5YzUzMWJjYTJjYjExNDg1ZmJlNzBkMmYzNzc3OGEzNmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9l6ZjF9NgW2MifMjL_xy9yEeZsWStMOvVfyOg6rVT-M">

해당 부분 원래 번역 되었던 것 맞나요?
기존 번역팩 넣어봐도 번역이 되는거 확인이 안되네요

**Comment by moonjigi0723** [comment]
번역안되잇길래 보내버린건데 다음부턴 번역여부도 확인해봐야겠네요...
