### ISSUE TITLE
Reinforced Walls+

### ISSUE THREAD

**Issue by moonjigi0723** [RimWorldKorea/RMK#199]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2882167814
- 모드 이름 : Reinforced Walls+
- 패키지ID : kinetictail.reinforcedwallsplus

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [O] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [아마도 그런거같아요] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>![image](https://github.com/RimWorldKorea/RMK/assets/152117758/5371579a-fbcf-4034-8f3a-6c4594dd9158)</b>
<p><--아무것도 번역 안되잇는거같습니다-->

**Comment by RimWorldKorea** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1929389479 1.3
