### ISSUE TITLE
Harvest Everything!

### ISSUE THREAD

**Issue by moonjigi0723** [RimWorldKorea/RMK#200]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2007485974
- 모드 이름 : Harvest Everything!
- 패키지ID : ogliss.ykara.harvesteverything

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [O] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [x] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>
<img src="https://github.com/RimWorldKorea/RMK/assets/152117758/ea9e0767-24ae-42b4-b7be-789a25366f59">
</b>
<p><--여기에 입력-->

**Comment by RimWorldKorea** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1500981707 1.0

**Comment by RimWorldKorea** [comment]
RKTM에서 같은 모더의 [다른 모드](https://steamcommunity.com/sharedfiles/filedetails/?id=2174246491)의 중복된 def를 번역하는 것으로 보임
해당 모드 자체에서는 패치로 번역 필요

오래 걸리는 작업
