### ISSUE TITLE
[FSF] FrozenSnowFox Tweaks  번역 갱신

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#224]
아 꼭 번역 업뎃하면 또 업뎃하더라

여우 얘는 한꺼번에 좀 업뎃했으면 좋겠다 ㄹㅇ

밑에거 말고 이걸로 추가 부탁

[[FSF] FrozenSnowFox Tweaks - 2893432492.zip](https://github.com/RimWorldKorea/RMK/files/13518845/FSF.FrozenSnowFox.Tweaks.-.2893432492.zip)

**Comment by RimWorldKorea** [comment]
이거 보니깐 뭐 추가되면 주소 죄다 깨지는 구조 같던데 어떰

**Comment by zilrty** [comment]
대충 말하면 노드를 12345...101 102 103.... 이렇게 해놓고 1에서 100까지는 a관련, 101부터 110은 b관련 이런식인데 각각 번호를 여유없이 지정해놔서 a관련 트윅 추가하면 1에서 101이 a, 102부터 111까지 b가 되니까 다 깨질수 밖에없음 ㅋㅋ
