### ISSUE TITLE
[FSF] FrozenSnowFox Tweaks

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#240]
또데이트로 인한 번역 업데이트

[[FSF] FrozenSnowFox Tweaks - 2893432492.zip](https://github.com/RimWorldKorea/RMK/files/13538744/FSF.FrozenSnowFox.Tweaks.-.2893432492.zip)

**Comment by RimWorldKorea** [comment]
아직 귀찮아서 위키를 안쓰고 있는데

작업할때 이렇게 해봐

**a. 출력 옵션 지정**
<img width="593" alt="화면 캡처 2023-12-04 180001" src="https://github.com/RimWorldKorea/RMK/assets/150018627/9906e5bd-19bc-4ddf-9485-0bc682244b8d">
<img width="592" alt="화면 캡처 2023-12-04 180017" src="https://github.com/RimWorldKorea/RMK/assets/150018627/a83cf455-5f25-4f94-b820-9244dbf66927">

**b. 노드 설정 (FSF Tweaks용)**
<img width="597" alt="화면 캡처 2023-12-04 180115" src="https://github.com/RimWorldKorea/RMK/assets/150018627/16937024-2c89-434f-9624-7c8c4d500150">
<img width="595" alt="화면 캡처 2023-12-04 180129" src="https://github.com/RimWorldKorea/RMK/assets/150018627/00299ceb-2bdb-4e0c-aef2-a96518323a85">

**c. xlsx 파일 추출**
<img width="592" alt="화면 캡처 2023-12-04 180143" src="https://github.com/RimWorldKorea/RMK/assets/150018627/79abb3d6-fa59-4927-9297-523407ac9075">

번역이 필요한 업데이트 같은거 있을때
이런 식으로 뽑아서 예전 번역이랑 비교해가면서 하면 됨

궁금한거 있을때마다 디스커션에다 ㄱㄱ
