### ISSUE TITLE
fish industry

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#247]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=758810805
- 모드 이름 : FishIndustry
- 패키지ID : 

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [ ] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [ ] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>[아리아넬](https://steamcommunity.com/profiles/76561198005158031) 3시간 전 
fish industry 모드도 번역이 빠진 것 같아요. 좋은 모드 감사합니다.

**Comment by RimWorldKorea** [comment]
무덤에서 확인
