### ISSUE TITLE
ㅇㅇ(220.92)  근데 림아토믹스랑 딥스토리지 바익 메카가 한글 적용이 안되는데 확인해줄수있을까

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#25]
라고 갤에 누가 댓글 남겼었음

근데 이거 이렇게 쓰는거 맞음? 깃헙 쓸줄 몰라잉

**Comment by RimWorldKorea** [comment]
방금 업뎃으로 해결 된거임

**Comment by RimWorldKorea** [comment]
아 이거 일부만 돼있네? 살펴봐야할듯

**Comment by RimWorldKorea** [comment]
오른쪽에 labels로 적당한 태그를 달아줄 수 있고
스레드가 더 이상 필요하지 않거나 종결해도 된다고 판단되면 아래에 close 또는 close with comment로 닫을 수 있음
