### ISSUE TITLE
Level Up!

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#254]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=1701592470
- 모드 이름 : Level Up!
- 패키지ID : 

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [ ] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [ ] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>[NEPH](https://steamcommunity.com/id/ezelline) 53분 전 
Level Up! 모드 등록 부탁합니다.

무덤에 있음

**Comment by RimWorldKorea** [comment]
모드 구조가 갈아엎힌 것 같음
전체 재번역 필요해보임

[Level Up! - 1701592470.xlsx](https://github.com/RimWorldKorea/RMK/files/13599920/Level.Up.-.1701592470.xlsx)
