### ISSUE TITLE
번역 갱신 및 추가

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#255]
[RMK 올릴거.zip](https://github.com/RimWorldKorea/RMK/files/13596306/RMK.zip)

업뎃
Big and Small Genes - 2920751126
Dragon's Descent - 2026992161

추가
Big and Small - Slimes - 3027202907
         Big and Small Races - 2894397737
         Biomes! Islands - 2038001322
         I'm off - 2873618148
         Industrial Revolution (Continued) - 2970472846
         Lamias, Sirens, Snakemen, and other Serpents-like beings - 2908225858
         Lost Psycasts - LightSeeker - 3068154233
         Nekomata, Giant Oni, and other Yokai - 3073163708
         Packable Containers - 3079237715
         Pathfinding Framework - 3070914628
         Pawn quick info - 3078081326
         Peer Pressure - 3057626086
         Tabula Rasa - 1660622094
         Vampires, Demons, and the Undead - 2926556467

------------------------------------------------------------------------

 Biomes! Islands - 2038001322 같은 경우는 무덤에 있는데

번역 요청이 들어온거라 무덤기반으로 다시 번역함

**Comment by RimWorldKorea** [comment]
작업을 뭘로 한거야? XML 수정해서 했음?

**Comment by zilrty** [comment]
ㅇㅇ xml 수정해서 함

작업할때 불편하면 담부턴 엑셀파일로 번역할게

**Comment by RimWorldKorea** [comment]
일단 그냥 다 집어넣긴 했는데 다음 번역할땐 xlsx 기반으로 작업해줘
아직 매뉴얼도 완성이 안됐고해서 원래 내가 알아서 변환해서 넣어놨는데
양이 이렇게 많으니깐 감당이 안되네

RMK 폴더에 xlsx 파일이 없는 번역 수정할땐 나한테 말해주면 변환해줌
특히 오래된 모드 옛날 번역은 불필요한 노드가 들어가있는 경우가 많아서
손질을 좀 할 필요가 있어 보이더라고

**Comment by zilrty** [comment]
@RimWorldKorea ㅇㅋㅇㅋ 알겠읍니다
