### ISSUE TITLE
A RimWorld of Magic

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#29]
#6

**Comment by zilrty** [comment]
이건 전부다 까본건 아닌데 RKTM에서 번역 빠진 부분만 RimMod KR에서 번역한것 같음

번역량이 압도적으로 RKTM이 많은데 지금 통합모드에는 RimMod KR 번역을 써서

번역이 거의 안되어있다고 보는듯

둘을 합치는 작업 전까지는 RKTM 번역을 쓰던가 해야할듯

**Comment by RimWorldKorea** [comment]
d6f162a710b93746599b277f242924b5947027c0
