### ISSUE TITLE
Runtime GC

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#32]
이거 걍 1.2 파일 넣어도 돌아가나?
1.4 좀비버전 번역본 따로 없겠지?

**Comment by Nubula01** [comment]
번역 자체는 내가 1.4버전으로 해둔게 있고 거의 변한거 없을테니 별 문제 없을듯 
근데 그거 요새도 쓰냐?

**Comment by RimWorldKorea** [comment]
안쓰는데 커뮤 자주 안오면 잘 모르는듯
근데 '번역이 왜 안되지? 검색해보자 -> 이제 안쓰는구나' 하도록 걍 빼버리는게 나은가 싶기도 하고
일단 안 급한거니깐 나중에 생각해보면 되겠지
