### ISSUE TITLE
번역추가요청

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#327]
Eccentric Tech - Spacer Furniture
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

Fists Aren't Made of Steel
https://steamcommunity.com/sharedfiles/filedetails/?id=2845980214

단 두개!

[번역.zip](https://github.com/RimWorldKorea/RMK/files/13726496/default.zip)

엑셀파일 포함 했고 이상한거 있으면 말해주삼

**Comment by RimWorldKorea** [comment]
파일은 아무 문제 없이 잘 돼있고
변환할 때 addthis 어쩌고 하는 텍스트 파일은 필요 없으니깐 그냥 지워도 됨
