### ISSUE TITLE
번역 업뎃 & 추가

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#340]
[FSF] FrozenSnowFox Tweaks - 2893432492
Biomes! Caverns - 2969748433
Biomes! Core - 2038000893
Biomes! Prehistoric - 2860715703
Eccentric Tech - Spacer Furniture - 3118185542
I Aint Building That - 3118060751
Mark That Pawn - 3056996662
Tabula Rasa - 1660622094

번역 업뎃

[Get Out Of My Chair!](https://steamcommunity.com/sharedfiles/filedetails/?id=3119651616)

번역 추가

[업로드 대기.zip](https://github.com/RimWorldKorea/RMK/files/13753520/default.zip)

업뎃한 애들 엑셀파일은 다 추가하긴했는데

중구난방에 막 만들어서 좀 지저분함

**Comment by RimWorldKorea** [comment]
217b6c171f48f7c58e44c42d761c695905c2c444 Biomes! Cavern 재확인 바람

**Comment by zilrty** [comment]
@RimWorldKorea

노드는 수정된거 그대로 쓰고 번역은 그 전걸 복붙해서 꼬였나봄

어렵다 어려워

[Biomes! Caverns - 2969748433.zip](https://github.com/RimWorldKorea/RMK/files/13757287/Biomes.Caverns.-.2969748433.zip)

**Comment by RimWorldKorea** [comment]
스팀엔 알아서 적당히 업데이트
