### ISSUE TITLE
Expanded Materials - Stones and Mortars

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#344]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2859334065
- 모드 이름 : Expanded Materials - Stones and Mortars
- 패키지ID : 

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [x] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [x] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>

https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972&tscn=1703470009

[이상한잉간](https://steamcommunity.com/profiles/76561198081386454) 6분 전 
Config error in VMEu_ConcreteMaking: description has trailing whitespace

Config error in EM_Mud: description has trailing whitespace

Config error in EM_Porcelain: description has trailing whitespace

Expanded material 모드들 관련해서 나오는 빨간줄 같습니다

**Comment by RimWorldKorea** [comment]
중요한거 아니라 다른데 얹어서 병합 예정
