### ISSUE TITLE
EPOE-Forked: Royalty DLC expansion

### ISSUE THREAD

**Issue by kimty0** [RimWorldKorea/RMK#353]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2008970276
- 모드 이름 : EPOE-Forked: Royalty DLC expansion
- 패키지ID : vat.epoeforkedroyalty

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [x] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [X] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>해당 모드에서 추가된 일부 물건들에 대한 번역이 되어 있지 않아서 문의드립니다.
혹시 필요하다면, 해당 모드의 xml 을 구글이나 파파고를 이용하여 기계번역하고, 문장을 다듬어서 파일 첨부로 올려도 괜찮을지 문의드립니다.
</p>

**Comment by RimWorldKorea** [comment]
번역은 언제나 환영입니다

가능하면 알파추출기 이용해서 xlsx 파일에 작업해주세요
관련 내용은 [여기](https://github.com/RimWorldKorea/RMK/wiki/4.-%EB%B2%88%EC%97%AD-%EA%B0%80%EC%9D%B4%EB%93%9C%EB%B6%81#%E2%85%B1-rmk-%ED%98%91%EC%97%85-%EA%B8%B0%EC%B4%88-%EC%A7%80%EC%8B%9D)에서 확인할 수 있어요

최종적으로는 작업한 xlsx 파일만 전달해주시면 됩니다

번역하는데 다른 어려움 있으면 추가로 연락 주세요

이 이슈는 일단 닫을께요
