### ISSUE TITLE
Save Our Ship 2 [1.4EXP]

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#36]
[https://gall.dcinside.com/m/rimworld/451427](url)

**Comment by Nubula01** [comment]
뭘 말하고싶은지 모르겠는데 한림 모드에 있던거 가져다 쓴거면 별 문제 없을텐데 
여태까지 따로 제보 들어온거도 없었고 정식버전 나오면 제대로 손보려고 놔두던 모드임

**Comment by RimWorldKorea** [comment]
한림 번역 수정 폴더에 있으면 기존 파일이랑 아예 하나로 합치려고 놔둬서 안돼있을 수도 있음
이거 내가 나중에 확인할께

**Comment by Nubula01** [comment]
ㄴㄴ 합치면 안돼 1.4 넘어오면서 싹 바뀌어서 에러나올거야

**Comment by Nubula01** [comment]
Nubula/S/Save Our Ship 2 폴더인가 그거 그대로 쓰면 됨

**Comment by RimWorldKorea** [comment]
제보사항 문제없는데 제보자한테 재확인 요청함
