### ISSUE TITLE
RuntimeGC [1.4]

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#372]
https://steamcommunity.com/sharedfiles/filedetails/?id=2983911897 <- 최신

아마 #32 에서 얘기한 버전이 [이거](https://steamcommunity.com/sharedfiles/filedetails/?id=2945201476)였던 것 같고

여전히 쓰는걸 권장하진 않지만 쓰는 사람이 있긴 하니 추가해도 될 듯?

#371

**Comment by Nubula01** [comment]
내용 차이 없을거같은데 기존 번역 그대로 가져다 쓰면 될듯

**Comment by RimWorldKorea** [comment]
@Nubula01
이거 네가 한 번 해볼래?

아직 자세한 가이드가 없긴 한데
[이거](https://github.com/RimWorldKorea/RMK/wiki/1.-%EB%B2%88%EC%97%AD-%EC%82%AC%EB%A1%80%EB%B3%84-%EB%A7%A4%EB%89%B4%EC%96%BC#xlsx-%ED%8C%8C%EC%9D%BC%EC%9D%B4-%EC%97%86%EB%8A%94-%EA%B8%B0%EC%A1%B4-%EB%B2%88%EC%97%AD%EC%9D%98-xlsx-%ED%8C%8C%EC%9D%BC%EC%9D%84-%EC%83%9D%EC%84%B1) 참고해서 RMK식 작업 프로세스를 한 번 익혀보는 의미로

**Comment by Nubula01** [comment]
평일은 시간이 안나는데 주말에 함 보겠음

**Comment by Nubula01** [comment]
링크 준 대로 함 해봤는데 XMLister라는 프로그램이 뭘 말하는지 모르겠네 
RKMTools.exe는 실행만 되고 바로 꺼지더라

**Comment by RimWorldKorea** [comment]
https://dotnet.microsoft.com/ko-kr/download/dotnet/7.0

여기서 `.NET 데스크톱 런타임 7.0.14` 다운받아서 설치해봐

**Comment by Nubula01** [comment]
깔고 재부팅해도 똑같네 
cmd로 접근해도 같은 거 보면 다른 문제가 있는거 아닐까

**Comment by Nubula01** [comment]
아니면 이 exe 파일을 기존 번역 파일이랑 같이 놔둬야 함?

**Comment by Nubula01** [comment]
아니면 이 변환기 소스코드라도 알려줘 
취미로 c# forms 만드는 놈이라서 소스코드정돈 읽을 수 있음

**Comment by csh1668** [comment]
@Nubula01
[RKMTools.zip](https://github.com/RimWorldKorea/RMK/files/13850017/RKMTools.zip)
소스코드는 이거에요

**Comment by Nubula01** [comment]
아까 받은거랑 다른 런타임 파일 받으라고 하네 아마 이게 문제인듯?

**Comment by Nubula01** [comment]
계속 경로를 못읽고 에러가 나서 뭐가 원인인가 했더니 폴더명이 너무 길어서 그런거였네 일단 추출 성공했음

**Comment by Nubula01** [comment]
일단 참고하란대로 해서 4번까지는 했는데 이제 이거 어떻게 하면 되냐

**Comment by RimWorldKorea** [comment]
이거 할때 어떤 식으로 했어? 혹시 손으로 일일히 맞춘건 아니지?

<img width="526" alt="화면 캡처 2024-01-07 223506" src="https://github.com/RimWorldKorea/RMK/assets/150018627/99c19df1-206c-44a9-8aea-5cc43e16d3eb">
<br><br>

일단 번역문은 `D열`이 아니라 `E열`에 넣으면 되고
작업한 흔적도 확인해보게 지우지 말고 다 남겨놔줘

**Comment by Nubula01** [comment]
들켰네 
지우지 말라는게 어떤걸 말하는거?

**Comment by Nubula01** [comment]
[RuntimeGC [1.4] - 2983911897.zip](https://github.com/RimWorldKorea/RMK/files/13853692/RuntimeGC.1.4.-.2983911897.zip)

일단 작업 완료함 
한림모드에 넣고 돌려봤는데 아무 문제 없이 적용되는거 확인 완료

**Comment by RimWorldKorea** [comment]
함수를 썼으면 쓴 흔적이 있을텐데 그걸 지우지 말라는 거였음 ㅋㅋ

이거 하나만 하면 끝나는게 아니라  
나중에 노드 천개 이천개짜리도 다룰 수 있을 정도로 강해져야 하기 때문에
수고스럽더라도 이걸로 시트를 다루는 연습을 좀 하고 넘어가자

일단 간단한 수준에서 무작정 따라하기 식으로 설명해보면

1. 알파 추출기로 뽑은 xlsx 파일에 시트를 하나 더 만들어서 거기에 csv 데이터 집어넣기
2. 메인 작업 시트 자투리 열에 `VLOOKUP` 함수를 이용해서 기존 번역 데이터를 긁어오기
3. 긁어온 데이터를 `값 붙여넣기`로 `E열`에 집어넣기

정도의 흐름으로 진행되는데
세부적으로 궁금한게 있으면 계속 물어봐
지금 제대로된 매뉴얼이 없는 상태라 막히면 너무 머리 싸매지 말고

[이건](https://github.com/RimWorldKorea/RMK/files/13400369/1201382956.xlsx) 참고할만한 예시 파일임
림매직 번역 파편화된거 하나로 합치는 작업이었던 것 같은데
함수가 어떤 식으로 쓰였는지 위주로 확인해보면 됨

**Comment by Nubula01** [comment]
보니깐 몇개빼곤 기존하고 똑같길래 눈으로 확인해서 대응시킨 다음에 쫙 긁어서 덮어씌웠지 
수천줄이었으면 나도 함수찾으러 갔음 ㅋㅋ 
어지간한건 다 if로 때워버리면서 하다보니 데이터베이스 함수는 잘 모르겠네 함 써보면서 익혀볼게

글고 별거아닌데 시간 오래걸린건 미안 토요일 오전에 편도선염 치료받는다고 병원갔다와서 뻗어버려서 주말에 해야했던게 한참 밀리다보니 일케 됐음

**Comment by RimWorldKorea** [comment]
만약에 함수 관련해서 참고자료 찾게되면 엑셀이 아니라 구글시트쪽 찾아보면 좋음
엑셀 매뉴얼은 사람이 보고 알아들으라고 만든 수준이 아닌데
엑셀이나 구글이나 웬만한건 거의 비슷해서 구글꺼 매뉴얼 보는게 편할거임

걍 구글링해서 유튜브나 블로거 공략집같은거 봐도 좋고

시간은 오래 걸려도 됨 어차피 오래 걸려도 되는거 맡긴거라 괜찮음

**Comment by Nubula01** [comment]
Xml까지 다 만들었는데 또 뭔가 할게 있나?

**Comment by RimWorldKorea** [comment]
파일 ㅇㄷ
