### ISSUE TITLE
궁금한게 두개 있는데

### ISSUE THREAD

**Issue by Nubula01** [RimWorldKorea/RMK#39]
1. 내가 이거 참여하는거랑 별개로 한림모드 자체는 계속 업뎃할건데 상관없지? 한림모드 자체가 내가 사용할 모드 번역해서 모아둔 저장소라 난 계속 쓸거거든 
2. 내가 새로 번역하거나 갱신한 파일은 어디로 주면 되냐? 깃헙 처음 써봐서 뭐가 뭔지 모르겠네

**Comment by RimWorldKorea** [comment]
1. 당연
2. 이거 나중에 교통정리해서 알려줄께. 그때까진 걍 한림에 올리고 알려주든가 해줘

**Comment by Nubula01** [comment]
ㅇㅋ 그럼 업뎃할때 꺼내가기 쉽게 날짜별로 파일 따로 넣어두고 xml 파일도 고쳐둘게
