### ISSUE TITLE
MakaiTech - Psycast

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#396]
https://gall.dcinside.com/m/rimworld/465276

> 초능력 배경부분 자동 번역안되서 따로 번역했는데 몬가..몬가 잘못되서 Korean파일에 초능력 배경부분만 모드파일에 다이렉트로 번역 때림..삼일전인가 갤럼한테 질문했었는데 번역까지는 했는데 이렇게해도 되는건지 아니면 안되는건지 모르겠네..모드 업데이트 되면 초능력 배경부분만 날라갈수도있어.. 이거또 양해바람

모드 내용 직접 바꾼거 있다는데 확인해보고 재작업 요청

[1.zip](https://github.com/RimWorldKorea/RMK/files/13885987/1.zip)

**Comment by RimWorldKorea** [comment]
<img width="536" alt="화면 캡처 2024-01-10 185955" src="https://github.com/RimWorldKorea/RMK/assets/150018627/cbf5bb0a-3454-43cc-a59c-e70fe609d346">

description 대신 tooltip으로 바꿔서 테스트해볼 것

**Comment by Nubula01** [comment]
글 가보니 이미 번역되어있다 해서 넣고 켜보니깐 실제로 번역되어있는데 
위에 테스트해보란 부분도 다른 번역이 있음 
뭘 테스트해보면 될까

**Comment by RimWorldKorea** [comment]
@Nubula01 

번역한 친구보고 테스트 해보라고 말한거긴 한데 네가 봐주고 싶으면 그래도 되고

번역 안되는 부분 모드 파일 직접 수정해서 번역했대서 다시 해보라고 적어둔거임

기존 번역보다 나아보이는 부분이 있어보여서

위 사항만 확인되면 내가 나중에 손 볼 예정

**Comment by RimWorldKorea** [comment]
검토 결과..

`VanillaPsycastsExpanded.PsycasterPathDef\tooltip` → 병합
`Keyed` → 번역은 돼있으나, 내부 인자가 모두 깨져서 사용 불가

그 외는 기존 번역이 나은 것으로 판단

**Comment by RimWorldKorea** [comment]
xlsx 변환만 진행하고 종결
