### ISSUE TITLE
Housekeeper Assistance Cat

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#45]
https://gall.dcinside.com/m/rimworld/451427
보고: RMK 적용 후 영어 출력

**Comment by RimWorldKorea** [comment]
번역 목록에 없음

**Comment by zilrty** [comment]
[HousekeeperAssistanceCat - 1541620640.zip](https://github.com/RimWorldKorea/RMK/files/13375968/HousekeeperAssistanceCat.-.1541620640.zip)

RKTM거랑 빠진거 번역해서 합침

**Comment by RimWorldKorea** [comment]
30e84ea5bfea49b8921daef767d0f237927aa0e1
