### ISSUE TITLE
[LC] Consolidated Traits

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#46]
https://gall.dcinside.com/m/rimworld/451427
보고: RMK 적용 후 영어 출력

**Comment by RimWorldKorea** [comment]
RMK 등록 안됨

**Comment by zilrty** [comment]
[[LC] Consolidated Traits - 2879753009.zip](https://github.com/RimWorldKorea/RMK/files/13377535/LC.Consolidated.Traits.-.2879753009.zip)

RKTM 거랑 빠진거 번역해서 합침

**Comment by RimWorldKorea** [comment]
11dde7fa35b669c9331dedaca3776eace9c7a560
