### ISSUE TITLE
Vanilla Races Expanded - Pigskin

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#491]
소스: https://m.dcinside.com/board/rimworld/471665
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3164798809
파일:

**Comment by RimWorldKorea** [comment]
지금 작업을 못하는 상황이라 이거 처리 "해줘"

아니면 일주일까지 밀릴 수도 있을 듯

**Comment by zilrty** [comment]
토요일이나 일요일쯤 번역갱신한거랑 같이해서 올리겠음둥

**Comment by zilrty** [comment]
임무 완수
