### ISSUE TITLE
Alpha Mechs

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#492]
소스: https://m.dcinside.com/board/rimworld/471864
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=2973169158

>rmk 목록에는 올라와 있는데 번역이 안되어 있음

**Comment by zilrty** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2975076039

이 한글화 모드의 내용만 가져왔어야 했는데 패키지아이디랑 모드 번호까지 가져와서 적용이 안된듯

LoadFolders.xml 수정 후 테스트 해보니 적용 잘되는거 확인함

이륙 허가 내려주면 싹 작업해서 스팀 업뎃까지 하겠읍니다

**Comment by RimWorldKorea** [comment]
지금 업로드된 데이터는 그 번역 모드(일반 번역 모드인지 포크인진 모르겠는데 하여튼) 다음에 나온 [갤번역](https://m.dcinside.com/board/rimworld/426728)이었던 것 같은데

그냥 DB랑 디렉토리만 알파 메크로 수정하면 될거임
