### ISSUE TITLE
Miho Facial Animation

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#510]
소스: https://arca.live/b/rimworld/100276452
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=2924786335
파일 주소: https://kioskloud.io/d/65e1f6a706c16ae89242207a-4LX5JKJBSWHHKZCCHBSTS52NK5NEQRCC
파일: 

@zilrty
이건 내가 나중에 할건데 파일만 미리 받아서 여기 올려줄래?
키오스크는 파일이 금방 터지는 경우가 있어서

**Comment by zilrty** [comment]
[1.zip](https://github.com/RimWorldKorea/RMK/files/14468735/1.zip)

여기 있읍니다

**Comment by RimWorldKorea** [comment]
허접이 뜨는 순간이 포착이 안돼서 테스트 진행이 안되는 중..
