### ISSUE TITLE
Kure's Rimworld of Magic Class Expansion Pack 번역 추가

### ISSUE THREAD

**Issue by MoongChiMayo** [RimWorldKorea/RMK#511]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2236103336&searchtext=magic
- 모드 이름 : Kure's Rimworld of Magic Class Expansion Pack
- 패키지ID : 2236103336

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [O] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [X] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
[Kure's Rimworld of Magic Class Expansion Pack - 2236103336.zip](https://github.com/RimWorldKorea/RMK/files/14468366/Kure.s.Rimworld.of.Magic.Class.Expansion.Pack.-.2236103336.zip)

<p><--여기에 입력-->
번역이안된 chef, ravenos 번역 추가

**Comment by RimWorldKorea** [comment]
@zilrty 
추가 번역분만 포함된 것 같은데 xml 유효성 문제 없으면 기존 폴더에 그대로 추가만 해줘

**Comment by zilrty** [comment]
@RimWorldKorea

엑셀파일 만드려고 보니 이거 원 번역본이 좀 이상함

 재번역 해야되나 싶은데 일단 번역추가본은 그냥 원본 xml에 복사 붙혀넣기로 해서 올리겠음

**Comment by RimWorldKorea** [comment]
그럼 일단 지금은 새로 추가된 파일만 업로드하고 추가로 봐야하는 부분은 새 이슈로 등록해줘
