### ISSUE TITLE
Kure's Rimworld of Magic Class Expansion Pack

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#515]
모드 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2236103336

사실 별 문제는 아닌데

번역을 안하고 영어를 그대로 박아놓은 것, 번역을 안하고 아무것도 작성 안한 것이 있음

그리고 아직 확인은 안해봤는데 노드도 바뀐 부분이 있는거 같음

위 부분 번역 안할거면 노드라도 지워놔야 누군가 '번역 안된 부분이네' 하고 번역하지 싶음

**Comment by MoongChiMayo** [comment]
아까 번역추가 올렸던사람인디 혹시 내가 뭐 잘못올린거야??

**Comment by RimWorldKorea** [comment]
@MoongChiMayo ㄴㄴ

@zilrty
원문 그대로 박아놓은건 상관없는데
번역 데이터 xml상에 노드는 있는데 내용이 비어있는건
그게 원문을 빈 내용으로 덮어씌워버리면 지워주는게 좋고
아니라면 냅둬도 상관없음

아님 아예 추출기 테스트용으로 써보는것도 좋겠지

**Comment by zilrty** [comment]
@RimWorldKorea 

ㅇㅇ 엑셀 파일 만들려고 보니 이상해서 말한거였음

보고 할만한 양이면 번역해서 엑셀 파일 만들고

아님 그냥 엑셀 파일만 만들어서 올리겠음
