### ISSUE TITLE
We Had a Trader (Continued), Camping Stuff, Research Reinvented Stepping Stones

### ISSUE THREAD

**Issue by 94HanA** [RimWorldKorea/RMK#518]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=1541408076
- 모드 이름 : We Had a Trader (Continued)
- 링크 : https://docs.google.com/spreadsheets/d/1x5xaSkR7abwyjV0aLIwDejSfQXo0es_P/edit?usp=sharing&ouid=108056244757570356952&rtpof=true&sd=true

<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=1523058989
- 모드 이름 : Camping Stuff
- 링크 : https://docs.google.com/spreadsheets/d/1KCysWZ7ikHzJoR9-8emnDTXo30JJfGo4/edit?usp=drive_link&ouid=108056244757570356952&rtpof=true&sd=true

<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2868389782
- 모드 이름 : Research Reinvented Stepping Stones
- 링크 : https://docs.google.com/spreadsheets/d/1cnN0U-pem4W967Ais_ekDp9WU9xZuE3X/edit?usp=drive_link&ouid=108056244757570356952&rtpof=true&sd=true

<b> 깃헙이 익숙치 않아 라벨 어떻게 붙이는지 모르겠습니다. 죄송합니다... </b>

<b> 처음 공유 드리는 부분이라 xlsx 서식이 올바르지 않을 수 있습니다. 혹여 제가 틀렸다면 다음 기회를 위해 이슈 스레드 닫기 전에 어떻게 하여야 좋은지 답변해주시면 감사하겠습니다. </b>

<b> Toddlers 모드의 번역 질이 좋지 않고 업데이트가 되어 있지 않아 개인적으로 번역해서 쓰고 있는데, 공유 드리기 위해 AlphaExtractor로 xlsx 추출이 되지 않아(모드 찍고 노드 불러오는 처음 시점부터 그냥 에러를 뿜네요) 어떻게 하면 좋을지 의문입니다. RimTrans로 추출하면 모든 노드가 오롯이 추출되지 않아 번역이 안 되는 부분이 있어 xml로 공유하기도 어렵습니다. 아래에 TraceBack 첨부합니다. 어떻게 하면 좋을지 답변해주시면 감사하겠습니다. </b>

Exception in Tkinter callback
Traceback (most recent call last):
  File "AlphaExtractor.py", line 742, in analysisOperation
  File "AlphaExtractor.py", line 698, in xpathAnalysis
  File "<string>", line 1
    "Things
    ^
SyntaxError: unterminated string literal (detected at line 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "AlphaExtractor.py", line 556, in onExtract
  File "AlphaExtractor.py", line 766, in extractPatches
  File "AlphaExtractor.py", line 712, in analysisOperation
  File "AlphaExtractor.py", line 717, in analysisOperation
  File "AlphaExtractor.py", line 748, in analysisOperation
  File "AlphaExtractor.py", line 236, in report
TypeError: write() argument must be str, not SyntaxError

**Comment by RimWorldKorea** [comment]
위에서 말한 Toddlers 모드가 [이거](https://steamcommunity.com/sharedfiles/filedetails/?id=2903359152) 맞나요?

**Comment by 94HanA** [comment]
네 맞습니다.

> 위에서 말한 Toddlers 모드가 [이거](https://steamcommunity.com/sharedfiles/filedetails/?id=2903359152) 맞나요?
> 
> p.s. 레이블은 관리자만 수정할 수 있습니다.
