### ISSUE TITLE
Days Matter (fork)

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#53]
#49

**Comment by zilrty** [comment]
[Days Matter (fork) - 2045496988.zip](https://github.com/RimWorldKorea/RMK/files/13377140/Days.Matter.fork.-.2045496988.zip)

RKTM 번역에서 빠진거 채우고 합침

**Comment by RimWorldKorea** [comment]
423a53f

**Comment by RimWorldKorea** [comment]
다음 릴리스시 종결: 스팀에 업데이트 하려고 파일을 다운받았을 때, 해당 파일에 이 부분이 반영되어 있는 상태
=> 더 이상 볼 필요 없지만 아직 스팀 업뎃은 안시켰으니 open 상태로는 남겨두고 나중에 지우자!

종결 태그 달아두면 내가 빼먹을 수도 있어서
이 상황에선 작업 완료 태그만 걸어놓으면 됨.

**Comment by zilrty** [comment]
아항 ㅇㅋㅇㅋ
