### ISSUE TITLE
Renamer 경고등

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#531]
@csh1668

Node.js 버전을 올리라네요? 이쪽에서 수정해줘야할 부분이 있는걸까요

Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by csh1668** [comment]
renamer.yml에서
actions/checkout@v3를 v4로
actions/setup-python@v4를 v5로 바꿔주면 돼요
