### ISSUE TITLE
Biomes! Fossils

### ISSUE THREAD

**Issue by 94HanA** [RimWorldKorea/RMK#534]
![image](https://github.com/RimWorldKorea/RMK/assets/111541485/d165c84c-a8ae-4b48-91a6-f0a764e8ac64)

이전 릴리즈에 추가된 Biomes! Fossils 모드의 레시피쪽 번역이 안 되어 있습니다. description은 되어 있는 것 같은데 타이틀만 빠진 것 같아요. 몇 개 안 되긴 할텐데 제가 할까요? (Biomes! 모드의 번역을 완성하고 있습니다.)

**Comment by RimWorldKorea** [comment]
#523

**Comment by RimWorldKorea** [comment]
<img src="https://github.com/RimWorldKorea/RMK/assets/150018627/900d0f6b-331c-40d6-b46f-e84bedc1ce7a" width=360><br>

정상적으로 뜨네요
림월드 버전이나 모드 목록 한 번 확인해보세요

**Comment by 94HanA** [comment]
![image](https://github.com/RimWorldKorea/RMK/assets/111541485/36937a31-ff9f-411e-9317-41712900a84c)
![image](https://github.com/RimWorldKorea/RMK/assets/111541485/36dce940-347b-4110-8e16-c6472cdc2c44)

림월드 1.4.3901 rev238
코어, Biomes! Fossils과 선행모드인 하모니, RMK만 넣은 상황에서 여전하네요.
RMK는 혹시 몰라 구독 해제 후 최신 릴리즈로 재다운로드 했음에도 여전히 그렇습니다.

이거 Toddlers 작업하실 때도 레시피def 관련해서 같은 말을 하셨는데, 제 생각엔 이거 뭐가 다른지 짚고 넘어가야 할 거 같긴 합니다.

![image](https://github.com/RimWorldKorea/RMK/assets/111541485/e17f0828-8136-4b55-b20c-688748b11428)

**Comment by RimWorldKorea** [comment]
Core\Languages\Korean (한국어)\Keyed\Misc_Gameplay.xml 884행에

    
    
    <RecipeMake>{0} 제작</RecipeMake>
    
    <RecipeMakeDescription>{0}(을)를 만듭니다.</RecipeMakeDescription>
    
    <RecipeMakeJobString>{0} 제작 중</RecipeMakeJobString>

내용이 존재하나요?

**Comment by zilrty** [comment]
잉 나도 번역되서 나오는데 뭔 문제지

**Comment by RimWorldKorea** [comment]
fossils 모드 언어폴더 확인해보셨나요

**Comment by 94HanA** [comment]
> fossils 모드 언어폴더 확인해보셨나요

이거였네요 제가 예전에 번역하려고 빼놓은 상태로 냅뒀나봄;; 귀찮게 해드려 죄송합니다 지금 아주 멀쩡해짐
