### ISSUE TITLE
Biomes! Oasis

### ISSUE THREAD

**Issue by 94HanA** [RimWorldKorea/RMK#535]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2538518381
- 모드 이름 : Biomes! Oasis
- 패키지ID : https://docs.google.com/spreadsheets/d/1h4HDO-l6Aghao74CDnLTnkQukwSxkwUc/edit?usp=sharing&ouid=108056244757570356952&rtpof=true&sd=true

**Comment by zilrty** [comment]
잉 오역 오타 수정인가여

아일랜드는 업뎃 안한거 같은데

**Comment by zilrty** [comment]
아 아일랜드가 아니라 오아시스구나

**Comment by 94HanA** [comment]
악 나는 바보 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by 94HanA** [comment]
라벨 번역 추가로 바꿔주세요 지송ㅅ,,,,
