### ISSUE TITLE
Ratkin Faction:Oberonia aurea

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#546]
소스: https://gall.dcinside.com/m/rimworld/474609
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3159926804
파일: [랫킨 제국 번역.zip](https://github.com/RimWorldKorea/RMK/files/14548343/default.zip)

>아쉽게도 배경설정의 설명은 코드가 안뽑혔음.

▲ 확인

**Comment by RimWorldKorea** [comment]
HAR 관련 추출기 조율 병행 중

**Comment by zilrty** [comment]
스팀 릴리즈 할라니까 요거 폴더 없다 그래서 그냥 로드폴더.xml 수정하고 릴리즈하겠음

합치는 과정은 안해도 되겠지?

**Comment by RimWorldKorea** [comment]
ㅇㅇ 내가 보는 중

폴더만 만들어놓고 올려놔

**Comment by RimWorldKorea** [comment]
https://github.com/RimWorldKorea/RMK/discussions/496#discussioncomment-8735877
