### ISSUE TITLE
[T] MoreFloors 1.4

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#57]
https://steamcommunity.com/sharedfiles/filedetails/?id=2878200208
#49

**Comment by zilrty** [comment]
[[T] MoreFloors 1.4 - 2878200208.zip](https://github.com/RimWorldKorea/RMK/files/13398988/T.MoreFloors.1.4.-.2878200208.zip)

**Comment by RimWorldKorea** [comment]
이건 왜 인코딩이 UTF-16인걸까

**Comment by zilrty** [comment]
엥 똑같이 작업한건데 뭐지 

적용은 잘되던데

**Comment by RimWorldKorea** [comment]
저러면 안되는 거긴 한데 작업 하는데 엄청 문제되는건 아니고
그냥 희귀종이라 신기해서 해본 말임 ㅋㅋ

**Comment by RimWorldKorea** [comment]
이거 파일에 주석처리 돼있는거 일부러 넣은거임? 노드는 유효한 것 같던데

TerrainDef 폴더에
 - MoreFloorsTerrainsCarpet
 - MoreFloorsTerrainsNatural

**Comment by zilrty** [comment]
ㅇㅇ 유효는 한데 쓸 필요는 없고 해서 주석 처리 해놓음

그 terraintempletdef 인가 걔네가 있어서

주석처리 부분이 쓸모가 없음

쓸거면 색상별로 노드를 다 작성해야하는데 몇몇 색상만 있고 해서 그냥 주석처리하고 남겨만 둠

**Comment by RimWorldKorea** [comment]
그냥 모드가 깔끔하게 안쓰여진거네?

**Comment by zilrty** [comment]
그런건가 어쨋든 혹시 몰라서 주석 처리한건데

지워도 될듯?

**Comment by RimWorldKorea** [comment]
cc0331261cd1b74e1c5a1496b04abe7e8e2976f0
