### ISSUE TITLE
Toddlers 추출 가능한가요?

### ISSUE THREAD

**Issue by 94HanA** [RimWorldKorea/RMK#588]
https://steamcommunity.com/sharedfiles/filedetails/?id=2903359152

#518 #524 처럼 AlphaExtractor로 추출이 되지 않고 있습니다.

모드 제작자분께 요청해서 하드코딩된 텍스트에 Translate key를 부여했다는 답변을 받았고, 1.5에 맞춰 재작업을 하려고 하는데요.

혹시 추출해주시는 거 가능할까요? 가능하다면 다음에 이런 일이 또 생기지 않도록 어떻게 하셨는지도 궁금합니다... 번거롭게 해드려 죄송합니다.

**Comment by RimWorldKorea** [comment]
모더가 이미 키를 언어 파일로 다 빼둬서 추출에 딱히 문제가 없는 것으로 보이네요
가지고 있는 모드 파일이 최신 버전이 맞는지 확인해볼 필요가 있을 것 같습니다

혹시 모르니 작업용 파일 첨부해둘께요

[2903359152.xlsx](https://github.com/RimWorldKorea/RMK/files/14771099/2903359152.xlsx)

**Comment by 94HanA** [comment]
감사합니다! 전 여전히 추출이 안 되네요..ㅋㅋ; 작업 완료했습니다.

https://docs.google.com/spreadsheets/d/1hNgrYR0eKYNHzPsM3CPuo2-y3zkeSvLi/edit?usp=sharing&ouid=108056244757570356952&rtpof=true&sd=true
