### ISSUE TITLE
Let's Have a Cat!

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#59]
ttps://steamcommunity.com/sharedfiles/filedetails/?id=1629060163
#49

**Comment by zilrty** [comment]
[Let's Have a Cat! - 1629060163.zip](https://github.com/RimWorldKorea/RMK/files/13399024/Let.s.Have.a.Cat.-.1629060163.zip)

**Comment by RimWorldKorea** [comment]
899d8a1fca1a12da2415c78045f18ba90bacc2a7
