### ISSUE TITLE
Razor Wire (With Damage)

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#61]
https://steamcommunity.com/sharedfiles/filedetails/?id=1501459305
#49

**Comment by zilrty** [comment]
[Razor Wire (With Damage) - 1501459305.zip](https://github.com/RimWorldKorea/RMK/files/13399050/Razor.Wire.With.Damage.-.1501459305.zip)

**Comment by RimWorldKorea** [comment]
f446961ca8f49471e4ea9027eb6bad5d7c96b3f9
