### ISSUE TITLE
Simply More Bridges (Continued)

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#62]
https://steamcommunity.com/sharedfiles/filedetails/?id=2012484790
#50

**Comment by zilrty** [comment]
Def 별로 나누는게 관리하기가 편한가

RKTM 다 좋은데 나눠논게 ㄹㅇ 극혐이네 찾기 줜나 힘듬

RKTM 번역은 유기된 버전이라 mile좌 컨티뉴 버전으로 대충 다시 번역함

[Simply More Bridges (Continued) - 2012484790.zip](https://github.com/RimWorldKorea/RMK/files/13348609/Simply.More.Bridges.Continued.-.2012484790.zip)

이거 이렇게 올려도 되는건지 모르겠네

**Comment by zilrty** [comment]
난 그냥 노트패드로 작업해서 엑셀파일은 없음
