### ISSUE TITLE
Concrete Walls

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#63]
https://steamcommunity.com/sharedfiles/filedetails/?id=795240891
#50

**Comment by zilrty** [comment]
[Concrete Walls - 795240891.zip](https://github.com/RimWorldKorea/RMK/files/13399105/Concrete.Walls.-.795240891.zip)

**Comment by RimWorldKorea** [comment]
946ff4241990fdd6b4e32b44196d095f1aefbea7
