### ISSUE TITLE
[HRK] Gun Nut - CORE

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#64]
https://steamcommunity.com/sharedfiles/filedetails/?id=2614317714
#50

연구쪽 일부가 엉뚱하게 번역된다고 함

**Comment by zilrty** [comment]
[[HRK] Gun Nut - CORE - 2614317714.zip](https://github.com/RimWorldKorea/RMK/files/13388573/HRK.Gun.Nut.-.CORE.-.2614317714.zip)

번역 수정함

**Comment by RimWorldKorea** [comment]
b48caad7519ddca14ec549a6fb3a5290a914c70e
