### ISSUE TITLE
Androids for RW 1.4

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#649]
소스 : https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=2889326293
파일 : [Androids for RW 1.4 - 2889326293.zip](https://github.com/RimWorldKorea/RMK/files/14896038/Androids.for.RW.1.4.-.2889326293.zip)

RKTM에 번역있던건데 누락 됐나봄

**Comment by RimWorldKorea** [comment]
노드 틀어진거 보여서 하는 김에 수정 진행
