### ISSUE TITLE
Vanilla Ideology Expanded - Memes and Structures

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#662]
소스 : https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=2636329500

모드 업데이트 한 부분이 번역안된듯

**Comment by RimWorldKorea** [comment]
제가 잠깐 손봐서 처리할 수 있는 분량이 아니네요

누군가 번역하길 기다려주세요~
