### ISSUE TITLE
Vanilla Races Expanded - Android

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#668]
소스 : https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=2975771801

"Vanilla Races Expanded - Android 에서 안드로이드 신체 부위 번역이 일부 누락되는 현상 발생

아마 바익 안드로이드가 업데이트되면서 세부적인 신체부위(예: 손가락, 흉골) 등을 통폐합했는데, 이 부분이 남아있어서 생기는 문제로 생각됩니다."

라고 제보가 들어옴

**Comment by RimWorldKorea** [comment]
추가 조사 필요

<img src="https://github.com/RimWorldKorea/RMK/assets/150018627/68236388-2404-4241-8de2-66e7dcf4617c" width=480 >

**Comment by RimWorldKorea** [comment]
바닐라 변경 사항 또는 프레임워크 문제로 의심됨

**Comment by RimWorldKorea** [comment]
바닐라 또는 바익 자체 문제로 보임

차후 업데이트 상황 모니터링

<img src="https://github.com/RimWorldKorea/RMK/assets/150018627/bb0a7e5e-fe4c-4e11-b891-70bb361968ad" width=480>
