### ISSUE TITLE
day matter (fork)

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#67]
창작마당 댓글

[Hb8](https://steamcommunity.com/profiles/76561198215646452) 8시간 전 
[RKTM] Mod에 포함된 day matter (fork) 모드번역이 제외된듯

**Comment by RimWorldKorea** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2045496988

**Comment by RimWorldKorea** [comment]
#53 중복
