### ISSUE TITLE
Auto Renamer Failing

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#68]
@csh1668 

시범적으로 한 번 써봤는데 중간에 뻗어버리네요..

확인 부탁드릴 수 있을까요?

[로그](https://github.com/RimWorldKorea/RMK/actions/runs/6863436835)

**Comment by csh1668** [comment]
@RimWorldKorea 

![스크린샷 2023-11-14 213540](https://github.com/RimWorldKorea/RMK/assets/18442452/c08471f6-f75b-4779-93ee-1fade6906d27)
Settings -> Actions -> General 들어가셔서
![스크린샷 2023-11-14 213638](https://github.com/RimWorldKorea/RMK/assets/18442452/d4796d52-5612-48df-834f-197bf78513ee)
위와 같이 권한이 허용되어있는지 확인해주실 수 있을까요


참고: https://github.com/ad-m/github-push-action/issues/96

**Comment by csh1668** [comment]
이번엔 다른 에러가 뜨네요 ㅋㅋㅋㅋ

아마 보호브렌치? 이걸로 설정된 거 때문에 그런거 같은데
https://livealife.tistory.com/4
여기처럼 푸시면 될 것 같아요

**Comment by RimWorldKorea** [comment]
아 보고계시는구나 ㅋㅋ

그건 풀 리퀘스트 거치라고 일부러 해둔건데
제가 메인에다 바로 꽂아서 그런 것 같아요

git에서 바로 브랜치 파는법 배우고 있는 중...

**Comment by csh1668** [comment]
작업용 브랜치를 따로 파고 Auto Renamer가 거기서만 작동하도록 하는 것도 좋을 것 같네요

**Comment by RimWorldKorea** [comment]
맞네 그 편이 낫겠네요
수정할 때마다 매번 가지치는 것도 바보같네요

**Comment by RimWorldKorea** [comment]
브랜치 보호 설정에서 merge시 pull request 요구 옵션을 꺼주면 작동을 하긴 하는데
'Allow GitHub Actions to create and approve pull requests' <- 이 옵션 딱봐도 저거 우회하라고 있는거 아닌가요???
왜 안되는거지?? ㅋㅋㅋㅋ

**Comment by csh1668** [comment]
현재, auto renamer는 pull request를 만드는게 아니라 바로 push를 해버립니다
그래서 옵션이 먹히지 않는 것 같네요

https://stackoverflow.com/a/72515781
이 방법에서 새로 계정을 파지 않고, 저나 선생님 계정을 사용해서 진행하면 가능할 것 같습니다.

**Comment by csh1668** [comment]
@RimWorldKorea 

![스크린샷 2023-11-16 114816](https://github.com/RimWorldKorea/RMK/assets/18442452/e6cd36ba-e0f9-47e8-be31-ad3be1f22a0f)
https://github.com/csh1668/RMK/blob/main/.github/workflows/renamer.yml
우선 renamer.yml를 다음과 같이 수정해야 합니다.


![스크린샷 2023-11-16 115207](https://github.com/RimWorldKorea/RMK/assets/18442452/4270eeaa-d006-4776-9c3c-c30748f75990)
https://github.com/settings/tokens
여기 들어가셔서 Generate new token (classic)을 눌러 액세스 토큰을 하나 만들어주세요.
이때 Select scopes에서 repo 섹션 체크박스를 다 체크해야 합니다.
완료하면 비밀번호 같은 게 나올텐데 이걸 복사하셔서


![스크린샷 2023-11-16 115446](https://github.com/RimWorldKorea/RMK/assets/18442452/57ff3864-801d-4180-b889-a3f1cc4baf64)
RMK -> Settings -> Secrets and variables -> Actions -> New Repository secret을 눌러
Name에 GH_ACTIONS_SECRET
Secret에 아까 복사한걸 붙여넣기 해주세요.


이렇게 하면 브랜치 프로텍션을 유지한 상태로 Auto Renamer만 풀 리퀘스트를 건너뛰고 푸쉬를 할 수 있게 됩니다.

이렇게 해도 안된다면 아마 브랜치 프로텍션에서 Do not allow bypassing the above settings 이게 체크되어있어서 안되는걸 겁니다.

**Comment by RimWorldKorea** [comment]
아침에 잠깐 해보다 안됐는데 이제 되네요 ㅋㅋ

 - fetch-depth는 추가하지 않아도 되었습니다. 1이 기본값이라는 것 같더라구요
 - 클래식 토큰 대신 Fine-grained Token을 썼고, 권한은 repo 전체가 아니라 content의 read/write 권한만 있어도 되었습니다.

이걸로 프로젝트 수명이 훨씬 늘어난 것 같습니다. 도와주셔서 정말 감사합니다!


p.s. 혹시 번역 관리에도 관심이 있다면 얘기해주세요. 더치맨엔 선장이 여러 명 필요하다..

**Comment by csh1668** [comment]
잘 해결돼서 다행입니다 ㅋㅋ

번역 관리가 RMK 단독사용으로 풀리는 번역을 제보하고 그런건가요? 림월드 하다가 발견하면 제보하겠습니다

Auto Renamer와 같은 자동화 작업과 관련해서 도움 필요하시면 언제든지 말씀해주세요
RMK 잘 쓰고 있습니다 ㅎㅎ
