### ISSUE TITLE
Dynamic Diplomacy - continued

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#695]
소스 : https://gall.dcinside.com/m/rimworld/489746
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=3220299022
파일 : [Dynamic Diplomacy - Continued - 3220299022.zip](https://github.com/RimWorldKorea/RMK/files/15020367/Dynamic.Diplomacy.-.Continued.-.3220299022.zip)

원 모드 (https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898) 번역이 RMK에 존재함

**Comment by RimWorldKorea** [comment]
기존 번역이 더 나아서 원래 있던 번역 그대로 사용함
