### ISSUE TITLE
Translated names

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#704]
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

특정 모드랑 충돌 하는듯?

**Comment by 94HanA** [comment]
테스트를 위해 다시 Translated names를 빼고 게임을 켰는데, 이번엔 정상 작동하고 있어 당황스럽습니다. 도대체 뭐가 문제인지 모르겠네요.. RMK가 최신 버전이 아니었던 것은 아닌데요. 일단 모드 목록은 드릴 수 있지만 이젠 이게 모드 충돌이 맞는지 아니면 아예 다른 원인인지도 잘 모르겠습니다.

<ModsConfigData>
    <version>1.5.4069 rev95</version>
    <activeMods>
        <li>zetrith.prepatcher</li>
        <li>brrainz.harmony</li>
        <li>ludeon.rimworld</li>
        <li>automatic.startupimpact</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
        <li>ludeon.rimworld.biotech</li>
        <li>ludeon.rimworld.anomaly</li>
        <li>unlimitedhugs.hugslib</li>
        <li>spoonshortage.adogsaidanimalprosthetics</li>
        <li>hana,a-music</li>
        <li>unlimitedhugs.allowtool</li>
        <li>porio.tunnulerfix</li>
        <li>swablu.ambience</li>
        <li>nals.facialanimation</li>
        <li>nals.facialanimationexperimentals</li>
        <li>erdelf.humanoidalienraces</li>
        <li>rooandgloomy.dragonianracemod</li>
        <li>ancot.dragonianfacialanimation</li>
        <li>oblitus.animalslogic</li>
        <li>com.bymarcin.architecticons</li>
        <li>notooshabby.awesomeinventoryforked</li>
        <li>mlie.bestmix</li>
        <li>mlie.bettermessageplacement</li>
        <li>falconne.bwm.tmpfix</li>
        <li>biomesteam.biomesfossils</li>
        <li>pathfinding.framework</li>
        <li>biomesteam.biomescore</li>
        <li>biomesteam.oasis</li>
        <li>biomesteam.biomesislands</li>
        <li>oskarpotocki.vanillafactionsexpanded.core</li>
        <li>regrowth.botr.core</li>
        <li>regrowth.botr.desertexpansion</li>
        <li>regrowth.botr.aspenforest</li>
        <li>regrowth.botr.borealforestexpansion</li>
        <li>regrowth.botr.temperateforestexpansion</li>
        <li>regrowth.botr.tundraexpansion</li>
        <li>biomesteam.biomesprehistoric</li>
        <li>automatic.bionicicons</li>
        <li>uuugggg.bloodymess</li>
        <li>bonible.mod.that.replaces.the.hive.spawn.sound.with.gore</li>
        <li>sov.visanderhedge</li>
        <li>crashm.colorcodedmoodbar.11</li>
        <li>brrainz.cameraplus_steam</li>
        <li>iforgotmysocks.caravanadventures</li>
        <li>reiquard.caravancolonistinfo</li>
        <li>void.charactereditor</li>
        <li>zylle.childboodbackstories</li>
        <li>zylle.childrensdrawings</li>
        <li>tiagocc0.colorblindminerals</li>
        <li>zylle.colors</li>
        <li>petetimessix.compacthediffs</li>
        <li>chris.cutercatearreplacer</li>
        <li>caesarv6.damageindicators</li>
        <li>alias.degeneralizework</li>
        <li>gguake.ai.dsfi</li>
        <li>dracoix.doormat.r12a</li>
        <li>telardo.dragselect</li>
        <li>eagle0600.dresspatients.1.4</li>
        <li>dubwise.dubsmintmenus</li>
        <li>dubwise.dubsperformanceanalyzer.steam</li>
        <li>swablu.flooding</li>
        <li>bonible.vanilla.gun.sound.replacement</li>
        <li>hawkwood.floorsarealmostworthless</li>
        <li>redmattis.geneextractor</li>
        <li>danielwedemeyer.generipper</li>
        <li>tac.genetrader</li>
        <li>klr.gloomyhairmk2forked</li>
        <li>syrus.heatmap</li>
        <li>hex.retexture</li>
        <li>fxz.solaris.ratkinracemod</li>
        <li>fxz.ratkin.facialanimation</li>
        <li>keshash.layeredwalldestruction</li>
        <li>krafs.levelup</li>
        <li>ratys.madskills</li>
        <li>m00nl1ght.mappreview</li>
        <li>thereallemon.mapreroll</li>
        <li>mlie.markthatpawn</li>
        <li>co.uk.epicguru.meleeanimation</li>
        <li>avilmask.microdesignations</li>
        <li>miho.fortifiedoutremer</li>
        <li>talos.miho.face.fa</li>
        <li>mlie.morefactioninteraction</li>
        <li>bichang.moresculpture</li>
        <li>zal.musicmanager</li>
        <li>issaczhuang.muzzleflash</li>
        <li>dvs.norandomrelations</li>
        <li>farmradish.nyaron</li>
        <li>talos.nyaron.face.fa</li>
        <li>densevoid.onebedtosleepwithall</li>
        <li>andromeda.packablecontainers</li>
        <li>tied.parkaretex</li>
        <li>fed1splay.pawntargetfix</li>
        <li>tr.qualcolor</li>
        <li>hatti.qualitybuilder</li>
        <li>mastertea.randomplus</li>
        <li>brrainz.rangefinder</li>
        <li>regrowth.botr.boilingforest</li>
        <li>regrowth.botr.swampexpansion</li>
        <li>regrowth.botr.tropicalexpansion</li>
        <li>temmie3754.retend.1</li>
        <li>mlie.realfactionguest</li>
        <li>mlie.realistichumansounds</li>
        <li>verniy709.realistichumansounds.harpatch</li>
        <li>mlie.relevantstatsindescription</li>
        <li>uuugggg.replacestuff</li>
        <li>brrainz.reversecommands</li>
        <li>jaxe.rimhud</li>
        <li>arandomkiwi.rimsaves</li>
        <li>rimsenal.evp</li>
        <li>rimsenal.federation</li>
        <li>rimsenal.feral</li>
        <li>rimsenal.core</li>
        <li>rimsenal.hair</li>
        <li>rimsenal.spacer</li>
        <li>rimsenal.spacermaid</li>
        <li>rimsenal.security</li>
        <li>rimsenal.storyteller</li>
        <li>rimsenal.french</li>
        <li>rimsenal.murica</li>
        <li>rimsenal.sophian</li>
        <li>rimsenal.techist</li>
        <li>rimsenal.urb</li>
        <li>rimsenal.askbarn</li>
        <li>rmk.translation</li>
        <li>telardo.romanceontherim</li>
        <li>automatic.gunplay</li>
        <li>rooandgloomy.yuranracemod</li>
        <li>roo.antyracemod</li>
        <li>roo.faanty</li>
        <li>cgf1.lightersteel</li>
        <li>mlie.showmeyourhands</li>
        <li>mlie.showmodupdates</li>
        <li>mlie.showmoddesignators</li>
        <li>petetimessix.simplesidearms</li>
        <li>uuugggg.smartmedicine</li>
        <li>sarg.smartspeed</li>
        <li>dhultgren.smarterconstruction</li>
        <li>cedaro.sortresearchtab</li>
        <li>andromeda.stackgap</li>
        <li>mlie.tabsorting</li>
        <li>cyanobot.toddlers</li>
        <li>superniquito.traiticons</li>
        <li>m00nl1ght.geologicallandforms</li>
        <li>biomesteam.biomescaverns</li>
        <li>avilmask.commonsense</li>
        <li>neronix17.tweaksgalore</li>
        <li>lat.veefaceforfacialanimation</li>
        <li>visibleraidpoints.1trickpwnyta</li>
        <li>wvc.sergkart.biotech.moremechanoidsworkmodes</li>
        <li>mlie.wehadatrader</li>
        <li>creeper.wealthhere</li>
        <li>revolus.whatsmissing</li>
        <li>mehni.pickupandhaul</li>
        <li>codeoptimist.jobsofopportunity</li>
        <li>won.hair</li>
        <li>won2.hair</li>
        <li>com.yayo.yayoani.continued</li>
        <li>mlie.yayoscaravan</li>
        <li>ancot.yuranfacialanimation</li>
        <li>cat2002.showhair</li>
        <li>frozensnowfox.filthvanisheswithrainandtime</li>
        <li>frozensnowfox.nodefaultshelfstorage</li>
        <li>dontstopthemusic.kv.rw</li>
        <li>nals.customportraits</li>
        <li>nals.dynamicportraits</li>
        <li>milsu.rimwaldo.vanilla</li>
        <li>sdknm2.qualityofbuilding</li>
        <li>lat.apparelretexture</li>
        <li>krkr.rocketman</li>
    </activeMods>

**Comment by RimWorldKorea** [comment]
당분간 이슈 유지하고 관찰

**Comment by RimWorldKorea** [comment]
https://gall.dcinside.com/m/rimworld/490812

**Comment by csh1668** [comment]
무슨 에러인지 알거같네요
![image](https://github.com/RimWorldKorea/RMK/assets/18442452/210967e0-640a-4584-ba99-bee5340246ae)
Translated names 내부에 있는 이런 것들 때문에 그럼
RMK 쪽으로 병합하면서 'Translated names'이름의 모드를 못찾아서 발생하는 에런데 Translated names가 깔린 유저들은 에러없이 잘 작동하지만 그렇지 않은 유저들은 에러가 발생합니다
또한 번역도 RMK쪽 번역이 아니라 기존 Translated names꺼가 들어갑니다

#710 
수정 해왔읍니다

**Comment by RimWorldKorea** [comment]
그럼 게임에 적용은 안하더라도 모드 폴더에 유지하고 있으면 에러가 안떴을 거란 말이네요?

이걸 찾고 다녔어야 할 생각을 하니깐 ㄹㅇ 막막하네

**Comment by csh1668** [comment]
Translated names 저 모드가 좀... 모딩 하는 사람들 입장에서 보면 코드가 개판입니다.
AllInstalledMods말고 그냥 바로 현재 모드 폴더를 가져오는 방법도 있는데😢
그래서 셤 끝나면 좀 다듬을 계획임다

**Comment by zilrty** [comment]
구아아아아악

**Comment by 94HanA** [comment]
이거 맞는 거 같습니다. 확실히 저도 Rimpy에서 RMK랑 Translated names 충돌 나는 거 보고 편입 확인해서, 아예 지웠었거든요. 근데 지우고 나서 며칠 림월드를 안 했고 그 다음에 킨 게 오늘이었는데 오늘 확인한 거였음. 별 수 없이 원래 있던 거 깔아서 넣고 하다가, 스팀 댓글 쪽 통해서 제보 부탁을 해주셔가지고 테스트를 했는데 당연히 테스트 때는 Translated names가 Active엔 없어도 설치 자체는 되어 있었으니깐...

**Comment by zilrty** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

[Sangun](https://steamcommunity.com/profiles/76561197994348604) 16분 전 
mac 이용자 입니다. Translated names 관련 오류가 mac 환경에서는 계속해서 발생하고 있습니다. dll 때문에 그런거 같은데 해결가능한 문제인가요?

라고 합니다

**Comment by RimWorldKorea** [comment]
맙소사 맥도 있구나
