### ISSUE TITLE
Mac 환경에서 Translated names 미적용

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#718]
소스: https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

>[Sangun](https://steamcommunity.com/profiles/76561197994348604)
mac 이용자 입니다. Translated names 관련 오류가 mac 환경에서는 계속해서 발생하고 있습니다. dll 때문에 그런거 같은데 해결가능한 문제인가요?

<img src="https://github.com/RimWorldKorea/RMK/assets/150018627/e9d5d412-bcaf-4a7e-9901-8e6a2bb17c10" width=200>

#704

**Comment by zilrty** [comment]
[Au Revior](https://steamcommunity.com/profiles/76561198083493101) 14분 전 
Translated names 라는게 폰의 이름들을 한글로 만들어주는 용도인가요? 혹시 사용하지 않는 방법도 있을까요? 지금 저의 현상은 폰의 이름을 캐릭터 에디터를 통해 영어로 바꿔도(인게임, 시작 시 두 경우 모두), 그게 어느 시점에 자동으로 한글로 변합니다.

라고 합니다

**Comment by RimWorldKorea** [comment]
테스트 브랜치 https://github.com/RimWorldKorea/RMK/tree/test_macOS

**Comment by RimWorldKorea** [comment]
피드백 https://gall.dcinside.com/m/rimworld/493073
