### ISSUE TITLE
Polarisbloc 시리즈

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#732]
소스 : https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972

모드 : Polarisbloc - Core LAB tmp port (https://steamcommunity.com/sharedfiles/filedetails/?id=3225348593)
          Polarisbloc - Security Force tmp port (https://steamcommunity.com/sharedfiles/filedetails/?id=3225387996)
          Polarisbloc - Mechenemy (https://steamcommunity.com/sharedfiles/filedetails/?id=2919759689)

" 항상 감사합니다.
폴라리스 시리즈 1.5 업데이트
기존 번역되있던 폴라리스 원작자 모드가 업데이트 없어 다른모더가 유지 "

라고 함미다

**Comment by RimWorldKorea** [comment]
tmp port 모드들은 안정화되면 느낌상 패키지ID 바꿀 것 같은데
그렇게 되면 바로 알려주세요
