### ISSUE TITLE
Translated Names, Multiplayer

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#733]
소스 : https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=2606448745

>[릇ᓚᘏᗢ](https://steamcommunity.com/profiles/76561198045054636)
멀티플레이 모드의 한글화가 업데이트된 이후로 멀티플레이 모드랑 충돌이 있는거 같아요. 새팩션 만들만고 새로시작하는 기능이 작동하지 않아요.

**Comment by RimWorldKorea** [comment]
@94HanA #654
멀티플레이어 모드는 제가 테스트해 볼 수가 없는데 확인 가능할까요?

**Comment by 94HanA** [comment]
일단 완전히 같은 내용의 한글화를 양쪽에 등록시켰기 때문에 이걸로 문제가 생겼을 가능성은 적고,(순서상 멀티플레이어 쪽에 응답이 느려서 RMK 쪽에 1.5 나오기 전에 먼저 넣어두었는데

멀티플레이어 쪽이 나중에 받아주어서 중복 등록이 된 상태) 멀티플레이어 모드 자체가 현재 1.5와 새 DLC에 맞게 업데이트가 안 된 상황이기 때문에(1.5 지원하는 걸로 나오지만 베타 상태. 버그 엄청 많음) 그쪽 관련일 가능성이 높습니다.

만약 관련해서 충돌로 정말 의심되는 부분이 있다면 RMK 쪽 멀티플레이어 번역을 제거해도 상관은 없지만(어차피 원본이 번역이 끝났으므로), 제 생각엔 아마 그게 문제가 아닐 거 같습니다.

**Comment by 94HanA** [comment]
개인적으로 하모니, 멀티플레이어, RMK만 넣고 실험해봤지만 문제가 재현되지 않습니다.

**Comment by stardish0703** [comment]
안녕하세요. 오류 문의 드린 릇입니다.
재현 영상 가져왔습니다. 
https://www.youtube.com/watch?v=IV5fokYayG4

하모니, RMK, 멀티플레이어 모드를 사용할때만 발생합니다. 
RMK모드를 제거하면 발생하지 않습니다.

해당 영상에 나오는 오류 로그입니다.
https://github.com/stardish0703/-/blob/main/log
저는 봐도 잘 모르겠어요 :D

RMK모드 정말 잘 사용하고 있습니다. 
언제나 감사드립니다.

**Comment by 94HanA** [comment]
해당 문제 재현 성공했습니다. 말씀하신대로 Multiplayer와 RMK를 동시 사용했을 때만 발생합니다.

단순 번역일 뿐이라 RMK Data 폴더에서 Multiplayer 폴더 통째로 빼도 문제는 여전히 발생합니다.
그래서 Multiplayer에 같은 번역이 다음 패치에 들어올 예정이라서 그냥 뺀다고 해결될 문제도 아니네요..

이 모드의 어떤 부분이 어디서 어떻게 충돌이 나서 이런 문제가 발생하는지 원인은 전혀 모르겠습니다.

**Comment by RimWorldKorea** [comment]
@94HanA 
RMK 안 넣은 상태에서 멀티플레이어에 번역만 넣고 돌렸을 때는 문제가 발생하나요?

**Comment by zilrty** [comment]
일단 저는 멀티플레이어에 번역만 넣고 돌리면 별다른 오류 없이 팩션 잘 만들어짐요

**Comment by 94HanA** [comment]
@RimWorldKorea 멀티플레이어"만" 넣고 돌렸을 때는 아무 문제가 없습니다.(번역을 넣든 말든). 반대로 RMK를 넣었을 경우 마찬가지로 문제가 생깁니다.(번역을 넣든 말든)

**Comment by zilrty** [comment]
이거 외지인 이름 번역이랑 충돌하는거 같은디요

이름번역 빼고 RMK랑 멀티플레이어 넣고 위에 영상대로 따라해봤는데 오류 안나고 팩션 잘 만들어짐

**Comment by 94HanA** [comment]
또 외지인 번역 너야?ㅋㅋㅋㅋㅋㅋ

**Comment by zilrty** [comment]
> 또 외지인 번역 너야?ㅋㅋㅋㅋㅋㅋ

대 지 인

**Comment by RimWorldKorea** [comment]
하모니를 써서 멀티플레이어 있으면 안돌아가게 해볼까..

**Comment by RimWorldKorea** [comment]
하모니로 멀티플레이어 동기화 코드를 집어넣을 수 있다는 것 같은데..

**Comment by RimWorldKorea** [comment]
[Data/Translated Names - NS4966146/1.5/Source/TranslatedNames/StaticConstructor.cs](https://github.com/RimWorldKorea/RMK/blob/bus/Data/Translated%20Names%20-%20NS4966146/1.5/Source/TranslatedNames/StaticConstructor.cs)

`pawn.Name = new NameTriple(translation, translation2, translation3);` 지점에서 pawn에 접근을 못해서 생기는 문제 같은데

일단 MultiFaction 기능이 1.5도 아니고 1.4버전 베타 기능이라
정상화 되기까지 좀 걸릴 것 같네

그 이후에 다시 살펴봐야할 듯

**Comment by 94HanA** [comment]
멀티플레이어 자체가 4월 16일 업뎃 이후로 굳어버린 상태라 여전히 테스트 버전이고..

**Comment by RimWorldKorea** [comment]
[멀티팩션 호환 베타 브랜치](https://github.com/RimWorldKorea/RMK/tree/dev_tn_compat)
멀티팩션 작동시 Translated Names 작동하지 않도록 조치

멀티팩션 자체가 1.5도 아닌 1.4버전 베타 기능이라
이걸 내가 개발자도 아닌데 어떻게 돌아가겐 못하겠고
게임 진행이 안되는 일은 없도록 그냥 우회만 시켜둠
