### ISSUE TITLE
Show Mod Updates

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#740]
소스: https://steamcommunity.com/sharedfiles/filedetails/?id=3079466972
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3218690663

>[BandoSouth](https://steamcommunity.com/id/BandoSouth)
해당 모드와 RMK 모드의 충돌이 발생하는 것 같습니다. 4월 26일 오후 1시 업데이트 직후부터 발생한 문제로 확인이 필요할 것 같습니다.

게임 실행시 크래시
신속히 처리 필요

**Comment by RimWorldKorea** [comment]
26일 이전 업데이트까지 돌려서 해봐도 전부 튕기는데? 뭐지?

**Comment by zilrty** [comment]
그냥 알티로 다시 추출해서 하니까 되는듯?

**Comment by RimWorldKorea** [comment]
혹시 뭐가 바꼈어서 안될까 싶어서 새로 뽑은게 지금 버스에 들어가 있는거거든? 다시 한 번 해봄

**Comment by RimWorldKorea** [comment]
지금까지 헛다리 짚은 거 같은데
그냥 혼자 넣고 돌려도 터지네

<img width="167" alt="화면 캡처 2024-04-27 110451" src="https://github.com/RimWorldKorea/RMK/assets/150018627/c3631277-780a-496f-82b6-bb8d73148179">

**Comment by zilrty** [comment]
엥 재추출한거 집어넣으니까 실행 잘되던데 뭐지

**Comment by RimWorldKorea** [comment]
Def 보면 Tabula Rasa에서 가져온게 있더라고?

1. Tabula Rasa 넣으면 안튕기고 돌아감
2. 근데 거기서 RMK 넣으면 또 터짐

ㅋㅋ

**Comment by zilrty** [comment]
![111111](https://github.com/RimWorldKorea/RMK/assets/132768180/2f6754a9-3ae4-4751-b388-6a2fdf4fbac0)

뭐지 난 재추출한거 넣으니까 안터지고 잘 돌아가는디

**Comment by RimWorldKorea** [comment]
일단 다른 거 먼저

**Comment by RimWorldKorea** [comment]
사례 https://gall.dcinside.com/m/rimworld/523345

**Comment by RimWorldKorea** [comment]
현재 Translated Names에서 해결하지 않고 #836 적용으로 해결 예정

**Comment by zilrty** [comment]
[[Rl]SunSetMoon](https://steamcommunity.com/profiles/76561198112521710) 20시간 전 
show mod updates 모드와 호환되지 않는다고 뜹니다. 어짜피 메인화면과 게임메뉴창에 뜨는 표시모드라 정상적으로는 플레이 가능은 합니다.

창작마당 댓글인데

작업 중이니 일단 기다려달라고 할까?

**Comment by RimWorldKorea** [comment]
내가 답글 달아줄께
