### ISSUE TITLE
Preemptive Strike 번역 누락

### ISSUE THREAD

**Issue by Nubula01** [RimWorldKorea/RMK#756]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2884952468
- 모드 이름 : Preemptive Strike (v1.4 Fork)
- 패키지ID : ltbob.preemptivestrike.rimworld

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [x] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [ ] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p><--여기에 입력-->

Preemptive Strike (v1.4 Fork) - 2884952468 이 모드 번역 누락됐더라. 목록에는 보이는데 겜 키면 없네
한림 버전 1.5로 대충 수정만 하고 돌리면 정상적으로 나오는거 봐선 가져다가다 누락된듯?

[Preemptive Strike (v1.xlsx](https://github.com/RimWorldKorea/RMK/files/15147983/Preemptive.Strike.v1.xlsx)

xlsx로 변환해서 가져왔음 뭐 딱히 추가된 건 없더라

**Comment by RimWorldKorea** [comment]
<img width="824" alt="화면 캡처 2024-04-29 222225" src="https://github.com/RimWorldKorea/RMK/assets/150018627/72d46588-d6a2-46e9-9d2f-2b1cf22bdb61"><br>

이거 1.3랑 1.4때 모드가 따로 있고 번역도 따로 있는데

번역 데이터가 완전 같지는 않는데 패키지id를 같이 쓴단 말이야

자세히 살펴보긴 시간이 없고 혹시 노드가 다를까 싶어서

아예 해당 버전에 해당 버전 번역만 들어가도록 나눠둔거임 ㅋㅋ

<br>
#681 에서 이런걸 좀 더 스마트하게 처리되도록 할 예정
