### ISSUE TITLE
[RH2] Rimmu-Nation² - Clothing

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#79]
https://steamcommunity.com/sharedfiles/filedetails/?id=2563506048
#76

**Comment by RimWorldKorea** [comment]
기존 번역 없음

추가 확인 필요

https://gall.dcinside.com/m/rimworld/451939

**Comment by zilrty** [comment]
Rimmu-Nation - Clothing (All Craftable!) - 1561492240

요놈의 번역이 RKTM에 있음

지금은 2달고 새로 나온만큼 RKTM 번역은 빠진것도 많고

RKTM에는 번역 된 노드가 [RH2] Rimmu-Nation² - Clothing 추출한 거에는 없는것도 있고 그럼

그냥 RKTM 거 쓰던가 기반으로 번역 다시해야할듯?

**Comment by RimWorldKorea** [comment]
대충 봤을 때 1이랑 2랑 다른 모드 같았는데 중복되는거 꽤 있었음?
1이랑 2랑 아예 관계없는거 아니지?

**Comment by zilrty** [comment]
ㅇㅇ 그냥 1에서 더 추가 한게 2인듯

그래도 혹시 모르니 노드 확인도 하면 좋을듯

**Comment by RimWorldKorea** [comment]
그냥 아예 다른 모드임
추가 확인 후 확인 안되면 종결

https://gall.dcinside.com/m/rimworld/451939
