### ISSUE TITLE
Set Up Camp

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#793]
소스 : https://gall.dcinside.com/m/rimworld/502860
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=3234938357
파일 : [Set Up Camp - 3234938357.zip](https://github.com/RimWorldKorea/RMK/files/15208574/Set.Up.Camp.-.3234938357.zip)

1.1-1.4 버전 번역 RMK에 존재

[SYR] Set Up Camp - https://steamcommunity.com/sharedfiles/filedetails/?id=1470065926

**Comment by RimWorldKorea** [comment]
번역면에서 변경점 없음
기존 번역 적당히 다듬기만 해서 사용

**Comment by RimWorldKorea** [comment]
근데 아무것도 달라진거 없고 패키지id도 같아서 번역이 안돼진 않았을건데?
