### ISSUE TITLE
A Dog Said... Animal Prosthetics 2

### ISSUE THREAD

**Issue by 94HanA** [RimWorldKorea/RMK#825]
<b>모드 정보</b>
- 워크샵 주소
-- (기존) https://steamcommunity.com/sharedfiles/filedetails/?id=746425621
-- (신규) https://steamcommunity.com/sharedfiles/filedetails/?id=3238353862
- 모드 이름 : A Dog Said... Animal Prosthetics -> A Dog Said... Animal Prosthetics 2
- 패키지ID
-- (기존) spoonshortage.ADogSaidAnimalProsthetics
-- (신규) SamBucher.ADogSaidAnimalProsthetics2

모드주 변경으로 인해 패키지ID 바꾸어야 합니다.

**Comment by RimWorldKorea** [comment]
오리지널 모드 번역 정리

**Comment by RimWorldKorea** [comment]
노드 전부 갈아엎힘
