### ISSUE TITLE
Prosthetic Didgets (Continued) 모드 미번역분 추가요청

### ISSUE THREAD

**Issue by minisier** [RimWorldKorea/RMK#831]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2012507402
- 모드 이름 : Prosthetic Didgets (Continued)
- 패키지ID : Mlie.ProstheticDidgets

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [x] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>
[Prosthetic Didgets (Continued) - 2012507402.xlsx](https://github.com/RimWorldKorea/RMK/files/15282867/Prosthetic.Didgets.Continued.-.2012507402.xlsx)

기존에 보철물 4종 번역만 있고 2종의 보철물 (simple finger/toe)에 대한 번역이 없어서
간단하게 6줄정도 번역했습니다 이렇게 올리는게 맞나요? 깃허브나 이런거 첨이라 잘못된부분있으면 수정하겠습니다
파일은 xlsx를 업로드했습니다

**Comment by RimWorldKorea** [comment]
다음엔 추출할 때 부터 xlsx로 해주시면 저희가 작업하기 좋아요 😎

**Comment by minisier** [comment]
아 옵션에 처음 추출부터 xlsx로 추출하기가 있네요 이제 확인했습니다 좋은 노력 항상 감사합니다 다음에도 기회가 있으면 잊지않고 xlsx로 작업하겠습니다
