### ISSUE TITLE
Designator Shapes

### ISSUE THREAD

**Issue by fongcrush** [RimWorldKorea/RMK#833]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=1235181370
- 모드 이름 : Designator Shapes
- 패키지ID : merthsoft.designatorshapes

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [ ] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?

<b>번역 작업 문외한이라, 뭐 파일 같은 거 없이 이렇게 요청하면 노양심인가요? 여기에 요청하라 적혀있어서요</b>

**Comment by RimWorldKorea** [comment]
창작마당에 안내되어 있듯이, 번역이 안 된 모드를 번역해 드리진 못합니다.
번역을 직접 해보길 원하시는 경우라면 저희가 도와드릴 수는 있어요.
