### ISSUE TITLE
새 이름 번역 모드 테스트

### ISSUE THREAD

**Issue by csh1668** [RimWorldKorea/RMK#836]
[KoreanName.zip](https://github.com/RimWorldKorea/RMK/files/15285958/KoreanName.zip)
![image](https://github.com/RimWorldKorea/RMK/assets/18442452/55d9a9ff-fef9-4848-82c8-f03bd3312998)
![image](https://github.com/RimWorldKorea/RMK/assets/18442452/cda908c6-f574-4441-805b-43bf7e5d2cf2)
일단 바닐라 기준 문제없이 되는거 같은데... 바로 PR 올리긴 좀 그래서 테스트 요청드립니다

- 당연히 기존 이름 번역 모드랑은 호환 안됩니다.
- 더러운 스파게티 코드에서 편ㅡ안한 코드로 다시 작성
- 작동 방식이 전혀 다릅니다. 기존은 폰을 생성할 때 바꿔치는 방식이라면 새 방식은 아예 로딩할 때부터 폰 생성 데이터 자체를 바꿔치는 방식 (개인적으로 훨씬 깔끔하다고 생각하는 방식)
- 자체 XML 방식에서 Strings 방식으로 변경
- 멀티플레이어 멀티팩션, 프리패쳐 관련해서 아무 이상 없는 것 확인했습니다
- 모드 설정에 이름 번역 기능을 끄는 기능, (개발자 모드가 켜져 있을 경우) 이름 데이터를 추출하는 기능이 있습니다 (TranslationReport처럼 바탕화면에 저장됨)
- 이름 번역 데이터는 Strings\Names\Translations.txt 여기에만 있으면 되며 다른 번역 데이터처럼 모드 폴더 내에서 위치를 바꿔도 상관 없습니다

**Comment by RimWorldKorea** [comment]
**1.**
일단 작동 방식이 정말 마음에 들어요. 딱 이랬으면 좋겠다 싶었는데.
기존 Translated Names 쓸 때 있었던 미묘한 버벅임도 없어져서 좋네요.
호환도 문제 없는거 확인했어요.

**2.**
지금 동작 설정을 바꿔도 저장되거나 하지 않아서 true로 고정되는 것 같아요

**3.** ⭐⭐⭐
스트링 파일에 기록되는 형식에 이름의 다른 메타데이터도 같이 포함할 수 있으면 그렇게 하는게 좋을 것 같아요
왜냐하면 이름이 들어가는 위치나 같이 조합되는 이름에 따라서 번역할 때 뉘앙스가 달라지는 부분이 있을 수 있거든요.

예시를 들면 같은 이름이라도 first나 last name이면 음차를 하는게 일반적인데,
nick name은 맥락에 따라서 굉장히 다양한 스타일로 번역이 될 수 있는 경우라던지..

예를 들면 `<{first}::{nick}::{last}>({type}){origin}->{target}` 식으로 해서

    <sukin::dikson::joe>(first)sukin->서킨
    <sukin::dikson::joe>(nick)dikson->딕슨
    <sukin::dikson::joe>(last)joe->조

이런 식으로? 만약 이런 데이터가 존재한다면 말이예요

모드 동작시에 사용되진 않더라도, 번역하는 사람들이 보고 참고할 수 있도록!

**4.**
번역 enable 설정의 의도된 동작 방식이 어떻게 되나요?
설정을 바꿀때 게임을 재시작해야 적용되는게 아니라
가능하면 실시간으로 될 수 있으면 좋을 것 같아요

이름풀을 바꿔치기할 때 기존 pawnbio 정보를 따로 저장해놨다가
enable 설정을 끄면 해당 정보로 다시 바꿔치기 한다던지?

근데 이거 멀티플레이어에서 어떨지 걱정되는데

**5.**
이름 추출할 때 완료되었습니다! 팝업이 필요할 것 같아요
내용엔 저장 경로라도 적어주면 딱일 듯 싶어요

+[브랜치](https://github.com/RimWorldKorea/RMK/tree/dev_new_names) 하나 파뒀어요

**Comment by RimWorldKorea** [comment]
@csh1668
아마 이번 주 안에 릴리스할 것 같아요!

주석.. 열심히 달았다...

**Comment by RimWorldKorea** [comment]
이거 번역자용 안내멘트 정도 추가하고 올리려고 하는데
다 끝나고 파일 보내드리면 맘에 안드는 부분 있나 한 번 보시고 PR 올려주실 수 있을까요?

이걸 제가 올려버리면 컨트리뷰트 같은게 안잡히지 않?나

**Comment by csh1668** [comment]
뭐 잘 작동만 한다면 상관없지 않을까요.. ㅎㅎ

**Comment by RimWorldKorea** [comment]
그럼 필요한 부분 마무리 하면 제가 적당히 슬쩍 올려버릴게요?
