### ISSUE TITLE
Tiny Workbenchs (Continued)

### ISSUE THREAD

**Issue by temporarygithubgeek** [RimWorldKorea/RMK#93]
Rimworld 1.4.3901(64-bit)
Tiny Workbenchs (Continued)
https://steamcommunity.com/sharedfiles/filedetails/?id=2387981423
mlie.tinyworkbenchs

**Comment by zilrty** [comment]
[Tiny Workbenchs (Continued) - 2387981423.zip](https://github.com/RimWorldKorea/RMK/files/13425082/Tiny.Workbenchs.Continued.-.2387981423.zip)
