### ISSUE TITLE
Ratkin: Promised land Ruleless Moustate

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#930]
소스: https://gall.dcinside.com/m/rimworld/522978
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3204817310
파일: [1.5.zip](https://github.com/RimWorldKorea/RMK/files/15497696/1.5.zip)

**Comment by zilrty** [comment]
https://m.dcinside.com/board/rimworld/523365

찐빠해결버전 올라옴

**Comment by RimWorldKorea** [comment]
수정 파일: [1.5.zip](https://github.com/RimWorldKorea/RMK/files/15503938/1.5.zip)
