### ISSUE TITLE
모드 3종 번역 추가 및 수정 요청

### ISSUE THREAD

**Issue by minisier** [RimWorldKorea/RMK#933]
<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193
- 모드 이름 : Common sense
- 패키지ID : avilmask.CommonSense

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [x] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [ ] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>
[Common Sense - 1561769193.xlsx](https://github.com/RimWorldKorea/RMK/files/15500026/Common.Sense.-.1561769193.xlsx)
기존에 없던 미 번역 부분 4줄을 번역
(기존 번역된 부분을 포함해야 하는건지, 새로 번역된 부분만 옮겨도 되는건지 몰라서 기존 번역에서 원래 존재하는 부분 전부 가져왔습니다)
(추출기를 통해 RMK \ avil \ 커먼센스 번역폴더에 존재하는 XML파일을 XML->XLSX로 변환하려고 했는데 변환이 안되고 빈 파일만 나옴. 잘 못쓰고 있는건지 모르겠어서 일단 수동으로 xml에서 텍스트 긁어서 가져왔음)

<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2879080074
- 모드 이름 : [CAT] Show Hair With Hats or Hide All Hats
- 패키지ID : cat2002.showhair

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [x] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [x] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>
[[CAT] Show Hair With Hats or Hide All Hats - 2879080074.xlsx](https://github.com/RimWorldKorea/RMK/files/15500087/CAT.Show.Hair.With.Hats.or.Hide.All.Hats.-.2879080074.xlsx)

https://gall.dcinside.com/mgallery/board/view/?id=rimworld&no=453762
이 문제가 아직도 있어서 영문명 Hide hat의 번역이 머리카락 숨김으로 되어있어서
이 옵션이 머리장비를 숨기는건지 머리카락을 숨기는건지 구분이 안되던 문제가 있었음
(디폴트옵션이라 굳이 안건드려도 되긴했음)
그걸 수정 하고 살짝 다듬음 원래 남의 번역은 건드리는게 아니라고 생각하는데 저건 문제가 있다고 생각해서 고침

<b>모드 정보</b>
- 워크샵 주소 : https://steamcommunity.com/sharedfiles/filedetails/?id=2264108215
- 모드 이름 : [XND] Visible Pants
- 패키지ID : XeoNovaDan.VisiblePants

<b>확인 사항</b> ([ ] 안의 공백을 지우고 x를 입력해주세요)
- [ ] [번역 목록](https://docs.google.com/spreadsheets/d/e/2PACX-1vTZtvMrguzs86lhnObgcacvtmTWJZ-H8ipgZcXdKC06GdfqADgZADk7kQxrftbZhJmP0uM9hRFtDoUK/pubhtml?gid=1757504801&single=true)에 모드가 등재되어 있나요?
- [ ] 이전에 번역이 되었던 부분에 대한 문제인가요?

<b>세부 설명 및 첨부 파일</b>
<p>
[[XND] Visible Pants - 2264108215.xlsx](https://github.com/RimWorldKorea/RMK/files/15500155/XND.Visible.Pants.-.2264108215.xlsx)
이것도 간단히 2줄정도 있는거 번역했음

**Comment by RimWorldKorea** [comment]
1. 커먼 센스는 확인해보니깐 문제없이 엑셀로 변환되는데
변환 경로가 ...\(RMK 경로)\Data\avil\Common Sense - 1561769193인지 체크해봐
논외로 이런 상황이 있을때 뭔가 여의치 않으면 추가분만 가져와도 알려만 주면 내가 알아서 함
혹시 갤에 글쓴거 너인가?

2. 원래 이런건 수많은 사람의 손때가 묻기 마련이니 다른 사람이 한 번역 수정하는거 너무 개의치 말어.

**Comment by minisier** [comment]
ㅇㅇ RMK태그 달고 추출기 질문한거 나 맞음
XML -> XLSX 추출 툴 누르고 Languages 폴더가 있는 루트 폴더를 지정해주세요. 창에서
...\workshop\content\294100\3079466972\Data\avil\Common Sense - 1561769193 폴더를 지정해서 했던건데
방금 또 해보니까 잘 되네 내가 뭔가 잘못 했던게 아닌가 십음 지금은 잘 되네 ㅈㅅㅈㅅ

항상 감사합니다
