### ISSUE TITLE
ResearchPowl

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#943]
소스: https://gall.dcinside.com/m/rimworld/522872
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=3236264529
파일: [ResearchPowl - 3236264529.zip](https://github.com/user-attachments/files/15515053/ResearchPowl.-.3236264529.zip)
참조: #927

**Comment by RimWorldKorea** [comment]
파일 누락

**Comment by zilrty** [comment]
[ResearchPowl - 3236264529.zip](https://github.com/user-attachments/files/15550407/ResearchPowl.-.3236264529.zip)

https://gall.dcinside.com/m/rimworld/526024

누락된거 올라옴
