### ISSUE TITLE
Spinal Engines for SOS2

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#959]
소스 : https://gall.dcinside.com/m/rimworld/524248
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=3254564110
파일 : [SOS2ExpSpinalEngines.zip](https://github.com/user-attachments/files/15521412/SOS2ExpSpinalEngines.zip)

**Comment by RimWorldKorea** [comment]
스크립트 수정해서 PR 넣어둠
반영되면 키 파일도 번역해서 올릴 예정
