### ISSUE TITLE
Integrated Implants

### ISSUE THREAD

**Issue by zilrty** [RimWorldKorea/RMK#974]
소스 : https://gall.dcinside.com/m/rimworld/526046
모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=3223443793
파일 : [Integrated Implants - 3223443793.zip](https://github.com/user-attachments/files/15550514/Integrated.Implants.-.3223443793.zip)

**Comment by RimWorldKorea** [comment]
공유 파일 그대로 사용했음
