### ISSUE TITLE
RazzleDazzle! (Continued)

### ISSUE THREAD

**Issue by hongcha-c** [RimWorldKorea/RMK#98]
RazzleDazzle! (Continued)
https://steamcommunity.com/sharedfiles/filedetails/?id=2024612321

**Comment by zilrty** [comment]
[RazzleDazzle! (Continued) - 2024612321.zip](https://github.com/RimWorldKorea/RMK/files/13438261/RazzleDazzle.Continued.-.2024612321.zip)
