### ISSUE TITLE
Compressed Raid

### ISSUE THREAD

**Issue by jooHG** [RimWorldKorea/RMK#99]
해당 모드가 (Abandonded) > (Continued) 로 넘어갔는데 전자만 번역에 포함 되어 있어서 요청 남김

RMK에 포함된 번역

Compressed Raid (Abandoned)
https://steamcommunity.com/sharedfiles/filedetails/?id=2377478084&searchtext=compressed

요청하는 번역
Compressed Raid (Continued)
https://steamcommunity.com/sharedfiles/filedetails/?id=2927368319&searchtext=compressed

**Comment by RimWorldKorea** [comment]
204c51b29c448a6da8794308aea62b7737c3883c

기존 번역 파일 구조가 현재 모드 구조와 안 맞는게 많아보이네요
