### ISSUE TITLE
Save Our Ship 2 함선 이름과 관련된 스크립트 처리 문제

### ISSUE THREAD

**Issue by RimWorldKorea** [RimWorldKorea/RMK#991]
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=1909914131

[참조]
https://gall.dcinside.com/m/rimworld/527213
https://gall.dcinside.com/m/rimworld/526881

**Comment by Nubula01** [comment]
SaveOurShip2.ShipDef 에서 <MechPsychicAmp.label>초능력 증폭선</MechPsychicAmp.label> 이거만 주석처리해서 적용안되게 하면 됨

**Comment by Nubula01** [comment]
원인은 다른 글 댓글에도 적었지만 스피크업때처럼 모더쪽에서 변수명인 defName을 기준으로 읽는게 아니라 변수출력텍스트인 label을 기준으로 읽어버려서 지랄나는거 
근데시발 1.4 베타에서는 증폭선이 안뜨는거땜에 시끄러워져서 고쳐놓고 왜 그다음 이벤트에서 또 빵꾸가 나는거야 화나네

**Comment by Nubula01** [comment]
일단 내가 내일 마지막 출근하고 저녁에 본가로 돌아가는거땜에 바빠서 다른 버그나 번역문제는 토요일 오후나 되야 검토 가능할듯
